import type { CodeGuidance } from "../activity-info";
import type { LessonCodeExample } from "../code-examples";
import type { Lesson } from "../course-data";
import type { LessonGuide, ObjectiveCoverage } from "../lesson-guides";
import type { LessonMotionStory } from "../lesson-motion";
import { plannedCourseManifests } from "../research-curriculum-manifests";
import { researchGuide, researchMotion } from "../research-courses/helpers";
import type { ResearchLabSpec, ResearchLessonSpec } from "../research-courses/types";
import type { WorldModelTransfer } from "../world-models/types";
import { embodiedCapstoneArtifactFiles, embodiedCapstoneEvidencePacks, embodiedCapstoneProjects } from "./capstones";
import { embodiedControlSpecs } from "./sections/control";
import { embodiedDataSpecs } from "./sections/data";
import { embodiedFoundationSpecs } from "./sections/foundations";
import { embodiedPerceptionSpecs } from "./sections/perception";
import { embodiedPolicySpecs } from "./sections/policies";
import { embodiedResearchSpecs } from "./sections/research";

const manifest=plannedCourseManifests.embodied;
export const embodiedSpecs:readonly ResearchLessonSpec[]=[...embodiedFoundationSpecs,...embodiedPerceptionSpecs,...embodiedDataSpecs,...embodiedPolicySpecs,...embodiedControlSpecs,...embodiedResearchSpecs].sort((a,b)=>a.lesson.number-b.lesson.number);
export const embodiedTracks=manifest.tracks.map((track)=>({...track,description:`${track.outcome} Each lesson extends one bounded perception-language-action system.`,role:"core" as const}));
export const embodiedLearningPhases=manifest.tracks.map((track,index)=>{const items=manifest.lessons.filter((lesson)=>lesson.track===track.id);return{id:track.id,index:String(index+1).padStart(2,"0"),title:track.title,range:`Lessons ${items[0].number}–${items.at(-1)!.number}`,tracks:[track.id],summary:track.outcome,milestone:items.at(-1)!.build};});
export const embodiedLessons:Lesson[]=embodiedSpecs.map((spec)=>spec.lesson);
export const embodiedLessonById=Object.fromEntries(embodiedLessons.map((lesson)=>[lesson.id,lesson])) as Record<string,Lesson>;
export const embodiedCurriculumMinutes=embodiedLessons.reduce((sum,lesson)=>sum+lesson.duration,0);
export const embodiedLessonGuides=Object.fromEntries(embodiedSpecs.map((spec)=>{const planned=manifest.lessons.find((lesson)=>lesson.id===spec.lesson.id)!;return[spec.lesson.id,researchGuide(spec,planned.build,planned.nextUse)];})) as Record<string,LessonGuide>;
export const embodiedObjectiveCoverage=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,[...spec.coverage]])) as Record<string,ObjectiveCoverage[]>;
export const embodiedMotionStories=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,researchMotion(spec)])) as Record<string,LessonMotionStory>;
export const embodiedTransferChecks=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,spec.transfer])) as Record<string,WorldModelTransfer>;
export const embodiedResearchLabs=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,spec.lab])) as Record<string,ResearchLabSpec>;
export const embodiedCodeExamples=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,spec.code])) as Record<string,LessonCodeExample>;
export const embodiedCodeGuidance=Object.fromEntries(embodiedSpecs.map((spec)=>[spec.lesson.id,spec.codeGuidance])) as Record<string,CodeGuidance>;
export const embodiedSynthesisMaps=Object.fromEntries(manifest.lessons.filter((lesson)=>lesson.capstone).map((lesson)=>{const items=manifest.lessons.filter((candidate)=>candidate.track===lesson.track);return[lesson.id,{title:lesson.title,intro:`Assemble ${lesson.build.toLowerCase()} with its complete decision and evidence chain.`,links:items.filter((candidate)=>candidate.number<=lesson.number).slice(0,-1).map((candidate)=>candidate.id)}];}));
export { embodiedCapstoneArtifactFiles, embodiedCapstoneEvidencePacks, embodiedCapstoneProjects };
