export const embodiedSources = {
  robotics: { title: "Gymnasium-Robotics documentation", url: "https://robotics.farama.org/", kind: "Documentation" as const, note: "Use the official environment documentation for goal-conditioned simulation interfaces, installation, and versioned task contracts." },
  probabilistic: { title: "Probabilistic Robotics", url: "https://mitpress.mit.edu/9780262201629/probabilistic-robotics/", kind: "Course" as const, note: "Read for sensor models, Bayes filtering, localization, calibration uncertainty, and data association." },
  dagger: { title: "A Reduction of Imitation Learning and Structured Prediction to No-Regret Online Learning", url: "https://arxiv.org/abs/1011.0686", kind: "Paper" as const, note: "Read for sequential covariate shift and collecting expert labels under learner-induced states." },
  act: { title: "Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware", url: "https://arxiv.org/abs/2304.13705", kind: "Paper" as const, note: "Read for action chunking with transformers, temporal aggregation, and an inspectable demonstration-driven manipulation system." },
  diffusionPolicy: { title: "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion", url: "https://arxiv.org/abs/2303.04137", kind: "Paper" as const, note: "Read for conditional denoising over action sequences, receding-horizon execution, and multimodal action distributions." },
  saycan: { title: "Do As I Can, Not As I Say: Grounding Language in Robotic Affordances", url: "https://arxiv.org/abs/2204.01691", kind: "Paper" as const, note: "Read for separating language-level usefulness from embodied affordance evidence during skill selection." },
  rt1: { title: "RT-1: Robotics Transformer for Real-World Control at Scale", url: "https://arxiv.org/abs/2212.06817", kind: "Paper" as const, note: "Read for tokenized image, language, and action interfaces plus dataset-scale robotic policy evaluation." },
  oxemb: { title: "Open X-Embodiment: Robotic Learning Datasets and RT-X Models", url: "https://arxiv.org/abs/2310.08864", kind: "Paper" as const, note: "Read for heterogeneous robot data, embodiment-specific action spaces, mixture construction, and cross-domain evaluation." },
  domainRandomization: { title: "Domain Randomization for Transferring Deep Neural Networks from Simulation to the Real World", url: "https://arxiv.org/abs/1703.06907", kind: "Paper" as const, note: "Read for deliberately varying simulator factors and testing transfer outside the training distribution." },
  libero: { title: "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning", url: "https://arxiv.org/abs/2306.03310", kind: "Paper" as const, note: "Read for task suites, distribution shifts, transfer protocols, and the limits of aggregate success." },
};
