import type { CapstoneEvidencePack } from "../capstone-evidence";
import type { CapstoneProject } from "../capstone-projects";
import { publicPath } from "../public-path";
import { rlSources } from "./sources";

type Seed = { lessonId:string; title:string; outcome:string; prerequisite:string; question:string; build:string; baseline:string; change:string; evidence:string; failure:string; source:keyof typeof rlSources; time:string };
const canonicalSeedCount = 5;
const seeds: Seed[] = [
  { lessonId:"tabular-control-capstone",title:"Build a tabular control workbench",outcome:"Deliver a tested finite MDP, exact solver, rollout evaluator, and changed-dynamics study.",prerequisite:"Agent loops, MDPs, beliefs, policies, and occupancy",question:"How does one transition change alter exact value, sampled return, and constraint feasibility?",build:"a three-state MDP with exact policy/value solutions and seeded rollouts",baseline:"slip probability .1",change:"raise slip to .3 with policy and evaluation budgets fixed",evidence:"exact values, rollout intervals, occupancy, success, and collision gate",failure:"a return-improving policy that violates the collision gate",source:"book",time:"3–5 hours" },
  { lessonId:"value-methods-capstone",title:"Build a value-learning agent",outcome:"Implement planning, Monte Carlo, TD, SARSA, and Q-learning behind one verified interface.",prerequisite:"Dynamic programming, returns, TD, and tabular control",question:"Which learner best meets the declared sample-efficiency and safety rule after dynamics shift?",build:"a finite environment with exact values and shared transition records",baseline:"matched baseline transition table",change:`evaluate held-out slip with ${canonicalSeedCount} canonical paired seeds`,evidence:"value error, interaction curves, occupancy, return, and constraints",failure:"one method with low TD loss and incorrect ending masks",source:"book",time:"4–7 hours" },
  { lessonId:"deep-value-capstone",title:"Build and diagnose DQN",outcome:"Implement a minimal DQN and run a seed-level target or exploration intervention.",prerequisite:"Function approximation, replay, target networks, DQN, and exploration",question:"Does one stability intervention improve return without Q-scale or reliability failure?",build:`a small discrete-control DQN with replay, target network, checkpoints, and ${canonicalSeedCount} canonical seeds`,baseline:"pinned target-copy interval and epsilon schedule",change:"alter one target, replay, loss, or exploration setting at matched interactions/updates",evidence:"return/AUC, Q scale, replay age, coverage, gradient checks, and failures",failure:"a NaN or exploding-Q seed retained in the artifact",source:"dqn",time:"6–10 hours; optional GPU" },
  { lessonId:"on-policy-capstone",title:"Build an on-policy actor-critic",outcome:"Implement policy gradients, GAE, critic updates, and a paired estimator intervention.",prerequisite:"Policy gradients, GAE, and actor-critic losses",question:"How does one lambda, entropy, critic, or clip change affect credit and bounded policy updates?",build:`a categorical actor-critic with rollout ownership, GAE, checkpoints, and ${canonicalSeedCount} canonical seeds`,baseline:"pinned GAE and update settings",change:"change one estimator or policy-update coefficient at matched interactions and epochs",evidence:"return, advantage variance, critic error, entropy, KL, clip fraction, and constraints",failure:"a seed crossing the KL or finite-value gate",source:"ppo",time:"6–10 hours; optional GPU" },
  { lessonId:"model-based-capstone",title:"Build a model-based agent",outcome:"Implement learned dynamics, CEM/MPC, uncertainty guard, and matched real-versus-model budgets.",prerequisite:"Learned dynamics, MPC, imagination, and model exploitation",question:"Does a longer or uncertainty-penalized planner improve realized outcomes at matched model calls?",build:"an action-conditioned model plus bounded MPC controller and fallback",baseline:"horizon-10 planner with fixed model-call budget",change:"alter horizon, ensemble penalty, or imagination ratio without changing real steps",evidence:"multistep error, predicted-real rank, return, model calls, constraints, and fallback",failure:"an off-support action whose predicted and realized ranking reverse",source:"book",time:"7–12 hours; optional GPU" },
  { lessonId:"sequence-policy-capstone",title:"Build a sequence policy from logs",outcome:"Create a causal trajectory policy and compare it with cloning under coverage gates.",prerequisite:"Behavior cloning, DAgger, offline coverage, and causal serialization",question:"Does sequence context improve trusted outcomes without unsupported critical actions?",build:"episode-split trajectory windows, cloning baseline, sequence model, and support guard",baseline:"behavior cloning on identical logged episodes",change:"causal sequence/return conditioning at matched data and updates",evidence:"action loss, leakage tests, desired-versus-real return, support, abstention, and trusted rollouts",failure:"a high-return condition choosing a zero-count action",source:"d4rl",time:"6–10 hours; optional GPU" },
  { lessonId:"rl-research-capstone",title:"Run an original RL intervention study",outcome:"Reproduce one released agent baseline and publish a controlled seed-level experiment.",prerequisite:"One completed agent capstone plus reproducible RL runs",question:"Does one predeclared mechanism change improve the chosen construct under matched budgets and hard gates?",build:"a learner-selected released RL agent with portable smoke/full profiles",baseline:"the reproduced configuration passing acceptance",change:"one estimator, data, exploration, model, planner, or constraint intervention",evidence:"all seed curves, paired effects/intervals, primitive budgets, failures, constraints, and alternatives",failure:"a negative, null, crashed, or strongest counterexample run",source:"book",time:"10–18 hours; optional GPU" },
];

function project(s:Seed): CapstoneProject { return { lessonId:s.lessonId,title:s.title,outcome:s.outcome,estimatedTime:s.time,
  prerequisites:[s.prerequisite,"Python 3 and local deterministic tests","Version control and evidence labels"],
  materials:[s.build,`Dependency-free starter: ${publicPath("capstone-artifacts/rl/rl_capstone_starter.py")}`,`Canonical ${canonicalSeedCount}-seed × two-arm reference matrix with per-row primitive budgets`,"The lesson code ladder and downloadable reference artifact","A local CPU environment for required checks","Optional pinned accelerator service for the labeled extension"],
  deliverables:[{title:"Verified system",description:`Implement ${s.build} with a manifest, assertions, and failure log.`},{title:"Matched intervention",description:`Reproduce ${s.baseline}; then ${s.change}.`},{title:"Evidence dossier",description:`Preserve ${s.evidence}, apply gates, and state a bounded decision.`}],
  stages:[
    {id:"specify",title:"Specify the decision system",goal:"Make the build and experiment falsifiable before code.",instructions:[s.question,`Pin ${s.build}.`,`Declare seed hierarchy, primitive budgets, metrics, gates, stop rule, and failure handling.`],checkpoint:"Another learner can predict pass, fail, and invalid outcomes.",hint:"Write every unit and independent experimental level.",workspacePrompt:"Record question, hypothesis, system interfaces, seeds, budgets, gates, and falsifier."},
    {id:"build",title:"Build and verify",goal:"Create the smallest complete working agent and prove deterministic contracts.",instructions:[`Run python3 rl_capstone_starter.py --project ${s.lessonId} --output ${s.lessonId}-starter.json; expect every printed check to be true. This executes a finite mechanism fixture, not agent training.`,`Replace the named fixture with ${s.baseline} while retaining the manifest, primitive-budget, raw-row, assertion, and evidence-boundary schema.`,`Run shape, target, ending, replay/rollout, tiny-fit, checkpoint, and seed-replay tests relevant to the method.`,`Preserve the first implementation failure and repair evidence.`],checkpoint:"Starter checks pass, then local system correctness and bounded baseline acceptance pass.",hint:"Do not launch long runs while one scalar target or resume step remains unexplained.",workspacePrompt:"Record starter output, implementation commands, invariant outputs, baseline rows, discrepancy, and repair."},
    {id:"intervene",title:"Run the changed case",goal:"Change one factor under matched evidence.",instructions:[`Execute: ${s.change}.`,`Preserve every row for ${s.evidence}.`,`Retain this failure: ${s.failure}.`],checkpoint:"Every declared seed/case has an artifact or predeclared exclusion.",hint:"Count interactions, updates, model calls, and runtime separately.",workspacePrompt:"Paste all seed rows, curves, paired effects, failures, and remaining confounds."},
    {id:"decide",title:"Apply gates and package",goal:"Make a reversible evidence-based conclusion.",instructions:["Apply constraints and finite-value gates before performance trade-offs.","Write the strongest alternative explanation and next falsifying experiment.","Export manifest, raw rows, curves, checkpoints, failures, analysis, and boundary."],checkpoint:"Human-readable report and machine-readable artifact agree.",hint:"A null or negative result is complete when the protocol passed.",workspacePrompt:"Write decision, bounded claim, uncertainty, residual risk, alternatives, and next test."},
  ],
  rubric:[{criterion:"Working system",developing:"Only a diagram or partial loop exists.",proficient:"End-to-end interfaces and local checks run.",excellent:"Targets, endings, resume, and failure-injection tests pass."},{criterion:"Experimental control",developing:"Several factors or budgets change.",proficient:"One change and matched core budgets are preserved.",excellent:"Paired seeds, primitive cost curves, gates, and stop rules are predeclared."},{criterion:"Failure learning",developing:"Failed seeds disappear.",proficient:"Failures remain and receive a diagnosis.",excellent:"A targeted retry distinguishes competing mechanisms."},{criterion:"Evidence honesty",developing:"One curve becomes a universal claim.",proficient:"Claims stay within environment, seeds, and budgets.",excellent:"Each stronger claim names missing evidence and a concrete reproduction."}],
  exemplar:{title:"A bounded RL evidence-contract reference",summary:`The reference specifies ${s.build}, supplies an executable deterministic starter, predeclares ${s.baseline} and ${s.change}, and demonstrates the artifact and gate logic for ${s.evidence}, including ${s.failure}. Its fixture rows do not claim that an agent was trained, a baseline was reproduced, or an intervention was executed.`,decisions:["Correctness checks required before a future comparison are explicit.","All five canonical seed-by-arm cells remain visible.","Hard-gate logic is demonstrated without inventing sampled performance."]},
  reflection:["Which invariant prevented the most expensive mistaken run?","Which support or budget confound could reverse the result?","What next intervention most efficiently falsifies the conclusion?"],
}; }

export const rlCapstoneProjects=Object.fromEntries(seeds.map((s)=>[s.lessonId,project(s)])) as Record<string,CapstoneProject>;
export const rlCapstoneEvidencePacks=Object.fromEntries(seeds.map((s)=>[s.lessonId,{
  starter:{title:`${s.title} evidence frame`,fields:[{field:"Question and falsifier",help:"Commit the causal comparison before final runs.",example:s.question},{field:"System and provenance",help:"Pin environment, algorithm, revisions, seeds, and budgets.",example:s.build},{field:"Baseline and intervention",help:"Name the control and one changed mechanism.",example:`${s.baseline}; ${s.change}`},{field:"Evidence and failure",help:"Keep raw units, gates, and failures.",example:`${s.evidence}; ${s.failure}`}]},
  reference:{title:`Reviewed evidence-contract reference for ${s.title.toLowerCase()}`,sections:[{heading:"1 · Contract",content:`${s.question} The fixture specifies ${s.build}; deterministic checks and planned comparison rows remain separate from sampled outcomes.`},{heading:"2 · Runnable mechanism start",content:`Run the downloadable starter with --project ${s.lessonId}; every printed check should be true. That proves finite fixture wiring only. Replace its mechanism with the working agent while preserving assertions, primitive budgets, and evidence schema.`},{heading:"3 · Baseline specification",content:`The proposed baseline is ${s.baseline}. The reference identifies the correctness and acceptance gates a future executed baseline must pass; it does not claim those training or rollout gates ran.`},{heading:"4 · Intervention specification",content:`The proposed change is ${s.change}. All five canonical seed-by-arm rows and their primitive budgets remain visible, including the failure-decision fixture: ${s.failure}. Fixture rows are not sampled performance.`},{heading:"5 · Decision boundary",content:`The proposed evidence is ${s.evidence}. A learner claim must stay within the exact implemented system, independent seeds, primitive budgets, and preserved run provenance.`}]},
  checks:[{label:"Question, system, and independent unit are explicit",terms:["question","system","seed"]},{label:"Runnable starter and working-agent checks are preserved",terms:["starter","agent","check"]},{label:"Baseline and treatment primitive budgets match",terms:["baseline","treatment","budget"]},{label:"Failure, uncertainty, and boundary are preserved",terms:["failure","uncertainty","boundary"]}],
  sources:[{label:rlSources[s.source].title,revision:"Primary or official source reviewed 15 Jul 2026; pin mutable implementations before execution",url:rlSources[s.source].url,readFor:rlSources[s.source].note,kind:rlSources[s.source].kind==="Paper"?"PRIMARY / FOUNDATIONAL PAPER":"OFFICIAL / TECHNICAL SOURCE"}],
} satisfies CapstoneEvidencePack])) as Record<string,CapstoneEvidencePack>;
export const rlCapstoneArtifactFiles=Object.fromEntries(seeds.map((s)=>[s.lessonId,{label:`${s.title} · JSON`,url:publicPath(`capstone-artifacts/rl/${s.lessonId}.json`),contents:["starter command and expected checks","canonical five-seed manifest","per-row primitive budgets","matched comparison fixture","failure decision trace","bounded evidence rule"]}])) as Record<string,{label:string;url:string;contents:string[]}>;
