import type { CodeGuidance } from "../activity-info";
import type { LessonCodeExample } from "../code-examples";
import type { Lesson } from "../course-data";
import type { LessonGuide, ObjectiveCoverage } from "../lesson-guides";
import type { LessonMotionStory } from "../lesson-motion";
import { plannedCourseManifests } from "../research-curriculum-manifests";
import { researchGuide, researchMotion } from "../research-courses/helpers";
import type { ResearchLabSpec, ResearchLessonSpec } from "../research-courses/types";
import type { WorldModelTransfer } from "../world-models/types";
import { rlCapstoneArtifactFiles, rlCapstoneEvidencePacks, rlCapstoneProjects } from "./capstones";
import { rlDeepValueSpecs } from "./sections/deep-value";
import { rlFoundationSpecs } from "./sections/foundations";
import { rlModelBasedSpecs } from "./sections/model-based";
import { rlOfflineSpecs } from "./sections/offline";
import { rlPolicySpecs } from "./sections/policy";
import { rlResearchSpecs } from "./sections/research";
import { rlValueSpecs } from "./sections/value";

const manifest = plannedCourseManifests.rl;
export const rlSpecs: readonly ResearchLessonSpec[] = [...rlFoundationSpecs, ...rlValueSpecs, ...rlDeepValueSpecs, ...rlPolicySpecs, ...rlModelBasedSpecs, ...rlOfflineSpecs, ...rlResearchSpecs].sort((a,b)=>a.lesson.number-b.lesson.number);
export const rlTracks = manifest.tracks.map((track)=>({ ...track, description: `${track.outcome} Each lesson extends one inspectable agent and evidence system.`, role:"core" as const }));
export const rlLearningPhases = manifest.tracks.map((track,index)=>{ const items=manifest.lessons.filter((lesson)=>lesson.track===track.id); return { id:track.id,index:String(index+1).padStart(2,"0"),title:track.title,range:`Lessons ${items[0].number}–${items.at(-1)!.number}`,tracks:[track.id],summary:track.outcome,milestone:items.at(-1)!.build }; });
export const rlLessons: Lesson[] = rlSpecs.map((spec)=>spec.lesson);
export const rlLessonById = Object.fromEntries(rlLessons.map((lesson)=>[lesson.id,lesson])) as Record<string,Lesson>;
export const rlCurriculumMinutes = rlLessons.reduce((sum,lesson)=>sum+lesson.duration,0);
export const rlLessonGuides = Object.fromEntries(rlSpecs.map((spec)=>{ const planned=manifest.lessons.find((lesson)=>lesson.id===spec.lesson.id)!; const nextId=planned.nextUse.includes(":")?planned.nextUse.split(":").at(-1)!:planned.nextUse; const nextTitle=manifest.lessons.find((lesson)=>lesson.id===nextId)?.title; return [spec.lesson.id,researchGuide(spec,planned.nextUse,nextTitle)]; })) as Record<string,LessonGuide>;
export const rlObjectiveCoverage = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,[...spec.coverage]])) as Record<string,ObjectiveCoverage[]>;
export const rlMotionStories = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,researchMotion(spec)])) as Record<string,LessonMotionStory>;
export const rlTransferChecks = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,spec.transfer])) as Record<string,WorldModelTransfer>;
export const rlResearchLabs = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,spec.lab])) as Record<string,ResearchLabSpec>;
export const rlCodeExamples = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,spec.code])) as Record<string,LessonCodeExample>;
export const rlCodeGuidance = Object.fromEntries(rlSpecs.map((spec)=>[spec.lesson.id,spec.codeGuidance])) as Record<string,CodeGuidance>;
export const rlSynthesisMaps = Object.fromEntries(manifest.lessons.filter((lesson)=>lesson.capstone).map((lesson)=>{ const items=manifest.lessons.filter((candidate)=>candidate.track===lesson.track); return [lesson.id,{ title:lesson.title,intro:`Assemble ${lesson.build.toLowerCase()} with its complete decision and evidence chain.`,links:items.filter((candidate)=>candidate.number<=lesson.number).slice(0,-1).map((candidate)=>candidate.id) }]; }));
export { rlCapstoneArtifactFiles, rlCapstoneEvidencePacks, rlCapstoneProjects };
