export type CapstoneProject = {
  lessonId: string;
  title: string;
  outcome: string;
  estimatedTime: string;
  prerequisites: string[];
  materials: string[];
  deliverables: { title: string; description: string }[];
  stages: {
    id: string;
    title: string;
    goal: string;
    instructions: string[];
    checkpoint: string;
    hint: string;
    workspacePrompt: string;
  }[];
  rubric: { criterion: string; developing: string; proficient: string; excellent: string }[];
  exemplar: { title: string; summary: string; decisions: string[] };
  reflection: string[];
};

export const capstoneProjects: Record<string, CapstoneProject> = {
  optimizers: {
    lessonId: "optimizers",
    title: "Explain one complete learning step",
    outcome: "Create a numerical field note that follows a tiny model from input tensor to updated weight, then predicts what a second step would do.",
    estimatedTime: "60–90 minutes",
    prerequisites: ["Tensors and shapes", "Softmax and cross-entropy", "Gradients and backpropagation", "Optimizers"],
    materials: ["Paper or a spreadsheet", "A calculator", "The four Foundations lesson labs", "Optional: a tiny Python/JavaScript notebook"],
    deliverables: [
      { title: "Shape map", description: "Label every tensor and axis in the forward pass." },
      { title: "Learning-step calculation", description: "Show logits, probabilities, loss, gradients, and one SGD or Adam-style update." },
      { title: "Verification note", description: "Use a finite-difference or second-step prediction to check your reasoning." },
    ],
    stages: [
      { id: "setup", title: "Define the tiny model", goal: "Make the problem small enough to calculate and strict enough to debug.", instructions: ["Use one input vector $x=[1,2]$, one weight vector $w=[0.2,-0.1]$, and target $y=1$.", "Define the logit $z=x \\cdot w$ and probability $p=\\operatorname{sigmoid}(z)$, or create two logits and use softmax.", "Write the shape beside every value. State which dimension is batch, feature, or class."], checkpoint: "Another learner can reconstruct the forward computation without guessing an axis or operation.", hint: "For the sigmoid version, $x$ and $w$ both have shape $[2]$, their dot product is scalar, and the binary target is scalar.", workspacePrompt: "Write your model contract, shapes, initial values, target, and forward equation." },
      { id: "forward", title: "Compute prediction and loss", goal: "Connect raw scores to a measurable error.", instructions: ["Calculate $z$, then $p$ to at least three decimal places.", "Calculate binary cross-entropy $$L=-[y \\log p +(1-y)\\log(1-p)].$$", "Explain in one sentence why the loss is large or small relative to the target."], checkpoint: "The probability is in $[0,1]$, the loss is non-negative, and the explanation agrees with the numbers.", hint: "With $y=1$, binary cross-entropy simplifies to $-\\log p$.", workspacePrompt: "Record the forward calculations and interpret the probability and loss in plain English." },
      { id: "backward", title: "Backpropagate and update", goal: "Show exactly how prediction error becomes a parameter change.", instructions: ["For sigmoid plus binary cross-entropy, use $\\partial L/\\partial z=p-y$.", "Use $\\partial z/\\partial w=x$ to obtain $\\partial L/\\partial w=(p-y)x$.", "Apply one SGD update $$w_{new}=w-\\eta \\nabla_w L,\\qquad \\eta=0.1.$$ State the direction each weight moves and why."], checkpoint: "The update should increase the target probability when the original prediction was too low.", hint: "If $y=1$ and $p<1$, then $p-y$ is negative. Subtracting a negative gradient increases weights attached to positive inputs.", workspacePrompt: "Show the chain-rule path, gradient values, updated weights, and a verbal direction check." },
      { id: "verify", title: "Verify and generalize", goal: "Demonstrate that your step is internally consistent rather than merely plausible.", instructions: ["Run the forward calculation again with $w_{new}$ and compare $p_{new}$ and $L_{new}$.", "Optionally perturb one weight by $\\epsilon=0.001$ and estimate the numerical gradient $$\\frac{L(w+\\epsilon)-L(w-\\epsilon)}{2\\epsilon}.$$", "Predict what changes if the learning rate becomes $10 \\times$ larger, then distinguish faster progress from overshoot."], checkpoint: "The new loss falls for the chosen small step, and analytical/numerical gradients agree closely if both are computed.", hint: "A correct local gradient predicts improvement for a sufficiently small step, not for every possible learning rate.", workspacePrompt: "Present the verification result, any discrepancy, and the learning-rate trade-off." },
    ],
    rubric: [
      { criterion: "Numerical correctness", developing: "Numbers appear without a traceable chain.", proficient: "Forward, gradient, and update calculations are correct.", excellent: "Includes independent checking and explains rounding or discrepancies." },
      { criterion: "Shape reasoning", developing: "Axes are missing or inconsistent.", proficient: "Every tensor and contraction is labeled.", excellent: "Uses shapes to prevent or diagnose a plausible bug." },
      { criterion: "Conceptual explanation", developing: "Says only that the model learns.", proficient: "Connects error, gradient sign, and update direction.", excellent: "Explains what changes under a different target, input, or learning rate." },
      { criterion: "Communication", developing: "Work cannot be reproduced.", proficient: "Assumptions and steps are clear.", excellent: "A beginner could follow the note without outside correction." },
    ],
    exemplar: { title: "A compact successful approach", summary: "Using the supplied sigmoid model gives $z=0$, $p=0.5$, and $L\\approx0.693$. The logit gradient is $-0.5$, so the weight gradient is $[-0.5,-1.0]$. With $\\eta=0.1$, $w$ becomes $[0.25,0.0]$. The new logit is $0.25$, probability $\\approx0.562$, and loss $\\approx0.576$: the local update moved in the predicted direction.", decisions: ["Kept the model scalar at the output so every derivative is inspectable.", "Used the second forward pass as an outcome check, not only an algebra check.", "Did not claim a larger learning rate is always better; the gradient is local."] },
    reflection: ["Which single intermediate value gave you the strongest evidence that the update was correct?", "Where would a shape or sign bug hide if you only inspected the final loss?", "How would Adam change the update calculation while leaving backpropagation unchanged?"],
  },

  "gpt2-from-scratch": {
    lessonId: "gpt2-from-scratch",
    title: "Build and debug a tiny GPT",
    outcome: "Produce a runnable decoder-only Transformer, a documented shape trace, and a training report that distinguishes correctness from fluent-looking output.",
    estimatedTime: "5–8 hours",
    prerequisites: ["Tokenization", "Embeddings and positions", "Causal attention", "Next-token loss", "Optimization"],
    materials: ["Python with PyTorch or an equivalent tensor library", "A small public-domain text file", "CPU is sufficient for a very small model", "Version control and a results notebook"],
    deliverables: [
      { title: "Tiny GPT implementation", description: "Tokenizer/data loader, causal blocks, loss, generation, and checkpointing." },
      { title: "Correctness dossier", description: "Shape trace, mask test, overfit-one-batch test, and resume test." },
      { title: "Experiment report", description: "Configuration, curves, samples, limitations, and one controlled ablation." },
    ],
    stages: [
      { id: "data", title: "Create the data contract", goal: "Make token boundaries, sequence windows, and targets explicit.", instructions: ["Begin with a character tokenizer or train a tiny BPE; reserve any special tokens deliberately.", "Split by document or contiguous region before creating windows to prevent neighboring leakage.", "Return $x[B,T]$ and $y[B,T]$, where $y$ is $x$ shifted one token into the future."], checkpoint: "Decode one batch and manually confirm every target is the next token and train/validation regions do not overlap.", hint: "For a sequence $[a,b,c,d,e]$, a length-4 example is $x=[a,b,c,d]$ and $y=[b,c,d,e]$.", workspacePrompt: "Document the corpus, tokenizer, split rule, $B/T$, and one decoded input-target pair." },
      { id: "model", title: "Implement and trace the model", goal: "Translate the architecture diagram into tested shape-preserving code.", instructions: ["Build token/position inputs, pre-normalized causal attention, MLP, residual connections, final norm, and vocabulary head.", "Assert the causal mask blocks every future position and check that each residual branch returns $[B,T,d]$.", "Record parameter count and initialize with a documented scheme."], checkpoint: "A forward pass returns logits $[B,T,V]$, a scalar loss with labels, and no position can change when only a future token changes.", hint: "Use a two-sequence test that shares a prefix but differs in its final token; earlier-position logits should match in evaluation mode.", workspacePrompt: "Paste or describe the module tree, forward shape trace, parameter count, and causal-mask test result." },
      { id: "train", title: "Prove it can learn", goal: "Debug on cheap evidence before running a real experiment.", instructions: ["Overfit one tiny batch until loss becomes very small; stop and debug if it cannot.", "Train on the small corpus with logged train/validation loss, gradient norm, learning rate, tokens/second, and fixed-seed samples.", "Save model, optimizer, scheduler, RNG, configuration, tokenizer, and data position; test resume."], checkpoint: "The micro-batch overfits, validation remains separate, and a resumed run continues without a mysterious reset.", hint: "Disable dropout for deterministic equivalence tests and restore train/eval modes deliberately.", workspacePrompt: "Record the overfit curve, first stable run, checkpoint fields, and one failure you diagnosed." },
      { id: "ablate", title: "Run one controlled ablation", goal: "Use the model to answer a design question rather than only produce samples.", instructions: ["Choose one change: remove position information, alter context length, change width, or disable weight tying.", "Hold data, token budget, seed policy, and evaluation protocol as constant as practical.", "Compare loss, speed, memory, and fixed-prompt samples; explain confounders and uncertainty."], checkpoint: "The conclusion names the exact treatment, control, evidence, and limitation rather than claiming universal superiority.", hint: "Ablations at tiny scale test mechanism and implementation, not frontier-model ranking.", workspacePrompt: "Write your hypothesis, control, treatment, metrics, result table, and one cautious conclusion." },
    ],
    rubric: [
      { criterion: "Correctness", developing: "Model trains but leakage/masking is untested.", proficient: "Shape, mask, shift, and overfit tests pass.", excellent: "Resume and deterministic control tests also pass." },
      { criterion: "End-to-end completeness", developing: "Only the model class exists.", proficient: "Data, training, evaluation, sampling, and checkpoints work.", excellent: "Interfaces and failure recovery are documented and reproducible." },
      { criterion: "Experiment quality", developing: "Shows one sample as proof.", proficient: "Uses curves, held-out data, and a controlled ablation.", excellent: "Reports uncertainty, efficiency, and plausible alternative explanations." },
      { criterion: "Understanding", developing: "Copies code without explaining shapes.", proficient: "Connects code to each architectural concept.", excellent: "Diagnoses a failure using causal information flow and numerical evidence." },
    ],
    exemplar: { title: "What a credible tiny run looks like", summary: "A 4-layer, width-128, 4-head character GPT trains on a document-level split. A 16-example micro-batch overfits before the main run. Validation loss, throughput, and fixed-seed samples are logged every 200 steps. Removing position embeddings worsens held-out loss and ordering-sensitive prompts while leaving the code path otherwise identical.", decisions: ["Started with characters to reduce tokenizer debugging, then documented the limitation.", "Tested causality by changing a future token and comparing earlier logits.", "Reported the position ablation as evidence at this scale, not a universal architecture result."] },
    reflection: ["Which test would have caught your most expensive bug earliest?", "What does your model learn that is not visible in a cherry-picked sample?", "Which GPT-2-era choice would you modernize first, and what controlled evidence would justify it?"],
  },

  "olmo3-case-study": {
    lessonId: "olmo3-case-study",
    title: "Audit and redesign an open pre-training flow",
    outcome: "Create an evidence-backed OLMo 3 stage audit and a scaled-down experiment testing one data, systems, or objective decision.",
    estimatedTime: "3–5 hours",
    prerequisites: ["Pre-training objective", "Scaling and optimization", "Data engineering", "Distributed systems", "Pre-training evaluation"],
    materials: ["OLMo 3 model-flow release", "Dolma 3 recipes", "OLMo configurations/checkpoints", "A spreadsheet or experiment-design notebook"],
    deliverables: [
      { title: "Model-flow map", description: "Dolma 3 Mix, Dolmino, and Longmino with artifacts, budgets, hypotheses, and evidence." },
      { title: "Stage audit", description: "One data, one systems, and one evaluation decision assessed critically." },
      { title: "Mini-replication proposal", description: "Control, treatment, budget, metrics, risks, and stop rule." },
    ],
    stages: [
      { id: "map", title: "Reconstruct the flow", goal: "Turn the release into a causal sequence rather than a list of claims.", instructions: ["Map 5.9T-token Dolma 3 Mix → 100B-token Dolmino → 50B-token Longmino.", "For each stage, record incoming checkpoint, data emphasis, objective/interface change, model family, and released artifacts.", "Mark which claims have configs, code, checkpoints, data procedures, logs, and independent evaluations."], checkpoint: "Every stage has a stated hypothesis and at least one measurement that could falsify it.", hint: "Broad capability, targeted math/code/QA/instruction, and long-context use are three different hypotheses.", workspacePrompt: "Write your stage table and evidence-strength legend. Note any missing links." },
      { id: "audit", title: "Connect data, scale, and systems", goal: "Use earlier lessons to interrogate implementation choices.", instructions: ["Audit source governance, deduplication, mixture weights, contamination, and document-level splits.", "Relate 7B/32B scale and token budgets to compute-optimal reasoning without treating one law as universal.", "Analyze reported 1,024-H100, 7.7K tokens/device/second scale: name likely parallelism, communication, and recovery concerns."], checkpoint: "Your audit separates published evidence, reasonable inference, and unanswered questions.", hint: "Use three labels—reported, inferred, unknown—so fluency does not turn guesses into facts.", workspacePrompt: "Record one strong design choice, one risk, one missing artifact, and one systems bottleneck." },
      { id: "evaluate", title: "Design the checkpoint evaluation", goal: "Show what each stage changed without letting a final score hide regressions.", instructions: ["Choose intrinsic loss, capability, memorization/contamination, and systems-health metrics.", "For Dolmino, compare target gains with broad-language forgetting; for Longmino, test use of distant evidence rather than accepted length alone.", "Freeze prompts, decoding, datasets, and scoring across checkpoints; include uncertainty and raw-output review."], checkpoint: "Each claimed gain has an entering checkpoint, a relevant control, and at least one regression slice.", hint: "Extra tokens are a confound unless the control receives the same token and schedule budget.", workspacePrompt: "Define the evaluation matrix, slices, paired comparison, and release/stop thresholds." },
      { id: "replicate", title: "Propose a scaled-down ablation", goal: "Preserve one OLMo hypothesis under a realistic learner budget.", instructions: ["Choose one variable, such as a targeted-code mixture or long-context stage, and create equal-compute control/treatment runs.", "Specify a tiny model/dataset, seeds, token budget, schedule, checkpoints, and evaluation protocol.", "List contamination, optimization, and hardware confounders; define what result would change your mind."], checkpoint: "The proposal can be executed by another learner and supports a narrow causal conclusion.", hint: "A 50M-parameter experiment can test whether a mixture changes a measured behavior without reproducing a 7B model.", workspacePrompt: "Write the experiment card: hypothesis, control, treatment, constants, metrics, budget, stop rule, and interpretation limits." },
    ],
    rubric: [
      { criterion: "Flow accuracy", developing: "Stages are vague or conflated.", proficient: "Budgets, purposes, and handoffs are correct.", excellent: "Connects each stage to specific inspectable artifacts and evidence." },
      { criterion: "Critical audit", developing: "Repeats release claims.", proficient: "Separates evidence, inference, risks, and unknowns.", excellent: "Identifies a falsifiable question and the missing evidence needed." },
      { criterion: "Evaluation design", developing: "Uses one aggregate benchmark.", proficient: "Includes stage controls and regression slices.", excellent: "Adds uncertainty, contamination, efficiency, and decision thresholds." },
      { criterion: "Replication proposal", developing: "Copies frontier scale or changes many factors.", proficient: "Tests one hypothesis under equal compute.", excellent: "Is reproducible and anticipates confounders and negative results." },
    ],
    exemplar: { title: "A strong narrow redesign", summary: "Test whether a targeted code mid-training mixture improves execution without broad forgetting. Branch one small base checkpoint into equal 2B-token runs: control continues the base mix; treatment uses 40% verified code with matched schedule. Compare held-out base loss, decontaminated execution tests, memorization, throughput, and three seeds at intermediate checkpoints.", decisions: ["Preserved token and optimizer budgets so the mixture is the main treatment.", "Used executable code tests plus broad loss, not code perplexity alone.", "Defined a go/no-go rule before viewing final samples."] },
    reflection: ["Which OLMo 3 claim became more or less convincing after you traced its artifacts?", "What part of the 1,024-GPU system cannot be meaningfully reproduced at tiny scale?", "How would a negative ablation result alter the next data or evaluation decision?"],
  },

  "tulu3-case-study": {
    lessonId: "tulu3-case-study",
    title: "Design a dual-purpose post-training stack",
    outcome: "Specify and evaluate an assistant that handles both exact tasks and open-ended research, using the right supervision and runtime controls for each.",
    estimatedTime: "4–6 hours",
    prerequisites: ["Supervised fine-tuning", "Preference optimization", "RL fundamentals and RLHF", "Tools and safety tuning", "Tülu 3 and DR Tulu"],
    materials: ["Tülu 3 paper and Open Instruct", "DR Tulu release", "A small prompt set with exact and research tasks", "Optional model API or local model"],
    deliverables: [
      { title: "Stage architecture", description: "A diagram and decision ledger for SFT, DPO, RLVR, RLER, and runtime controls." },
      { title: "Data and reward specification", description: "Example records, label rubrics, verifiers, and known shortcuts." },
      { title: "Evaluation and launch memo", description: "Paired checkpoint tests, safety/cost slices, and go/no-go decision." },
    ],
    stages: [
      { id: "tasks", title: "Define two task families", goal: "Make the difference between exact and open-ended outcomes operational.", instructions: ["Create at least five exact tasks with stable machine-checkable outcomes and five research tasks requiring current sources.", "For each, specify user success, severe failure, available supervision, tools, and maximum cost.", "Write one ambiguous boundary example that should ask a clarifying question."], checkpoint: "A reviewer can tell which outcomes support exact verification and which require a multi-dimensional evolving rubric.", hint: "Exact does not mean easy; it means correctness can be reliably checked after parsing.", workspacePrompt: "Describe both task families, success/failure definitions, tools, and supervision available." },
      { id: "recipe", title: "Place SFT, DPO, RLVR, and RLER", goal: "Use the simplest learning signal that expresses each desired behavior.", instructions: ["Use SFT for ideal response/tool trajectories and uncertainty/clarification examples.", "Use length-normalized DPO for relative relevance, clarity, and boundaries, mixing off-policy diversity with on-policy mistakes.", "Use RLVR only where verifiers are stable; use online RLER for research criteria that evolve with gathered evidence."], checkpoint: "Every stage names its incoming model, data, objective, intended change, and possible regression.", hint: "Do not add RL merely because it is last; add it when sampled outcomes supply information demonstrations do not.", workspacePrompt: "Write the stage ledger and one training record example for each supervision format." },
      { id: "runtime", title: "Design the tool and safety boundary", goal: "Keep authorization outside the learned policy.", instructions: ["Define MCP-style search/browse tools with schemas, scoped credentials, source provenance, and error behavior.", "Add permission checks, sandboxing, confirmation for consequential actions, token/tool budgets, and termination rules.", "Test an indirect prompt injection embedded in a source and a citation that does not entail the claim."], checkpoint: "A malicious document cannot gain tool authority even if the model follows its text.", hint: "The policy proposes tool calls; deterministic code authorizes and executes them.", workspacePrompt: "Document the trust boundaries, allowed/forbidden actions, validation, and two attack tests." },
      { id: "evaluate", title: "Compare stages and decide", goal: "Prove that each added stage creates value without hiding cost or regressions.", instructions: ["Evaluate base/SFT/DPO/RL checkpoints under identical prompts and decoding.", "For exact tasks report pass rate and verifier spoofing; for research report coverage, citation entailment/source quality, synthesis, tool cost, and evaluator drift.", "Include broad capability, over-refusal, invalid actions, latency, and cost, then write a go/no-go recommendation."], checkpoint: "The recommendation cites target gains, uncertainty, regressions, runtime risks, and rollback conditions.", hint: "A reward curve is training telemetry; a launch decision needs independent outcome measurements.", workspacePrompt: "Build the results table and write the launch decision with one condition that would reverse it." },
    ],
    rubric: [
      { criterion: "Method selection", developing: "Lists algorithms as a fixed ladder.", proficient: "Matches SFT, DPO, RLVR, and RLER to available judgments.", excellent: "Uses controls to show the marginal value of each stage." },
      { criterion: "Reward/data design", developing: "Supervision is underspecified.", proficient: "Provides records, rubrics, and verifier contracts.", excellent: "Anticipates length bias, spoofing, drift, and on-policy distribution shift." },
      { criterion: "Runtime safety", developing: "Relies on a safety prompt.", proficient: "Uses least privilege, validation, budgets, and confirmation.", excellent: "Includes adversarial tests, incident evidence, and recovery." },
      { criterion: "Evaluation", developing: "Reports one aggregate reward.", proficient: "Separates exact, research, safety, and cost outcomes.", excellent: "Uses paired checkpoints, uncertainty, raw review, and a defensible ship rule." },
    ],
    exemplar: { title: "One coherent stack", summary: "SFT teaches calculator and research trajectories; length-normalized DPO improves relevance from off/on-policy pairs. RLVR optimizes exact calculator outcomes against a hardened parser. RLER trains research trajectories with task-specific coverage and evidence rubrics. Runtime code scopes search/browse, blocks injected instructions, caps tool calls, and validates citations. Release requires gains over DPO on both task families without tool-safety or broad-capability regression.", decisions: ["Kept exact and open-ended reward streams separate.", "Treated RLER’s evaluator as a changing model that needs calibration, not ground truth.", "Made authorization deterministic and reversible outside the weights."] },
    reflection: ["Which stage would you remove first under half the budget, and what capability would you expect to lose?", "Where can on-policy data improve relevance but also narrow diversity?", "Which failure belongs in training, which in evaluation, and which must be blocked by runtime architecture?"],
  },

  "test-time-compute": {
    lessonId: "test-time-compute",
    title: "Design and benchmark an inference service",
    outcome: "Build a capacity plan and small benchmark that jointly controls decoding quality, KV memory, quantization, batching, and reasoning budget.",
    estimatedTime: "3–5 hours",
    prerequisites: ["Decoding and sampling", "Generation loop and KV cache", "Quantization", "Serving systems", "Test-time compute"],
    materials: ["A local model server or API with usage/latency data", "A 20+ prompt workload", "A spreadsheet or plotting tool", "Optional GPU metrics"],
    deliverables: [
      { title: "Workload and SLO", description: "Prompt/output distribution, concurrency, quality target, and percentile latency/cost limits." },
      { title: "Benchmark matrix", description: "Controlled comparisons across decoding, precision, batching, and reasoning budgets." },
      { title: "Capacity recommendation", description: "Chosen configuration, overload policy, evidence, and limitations." },
    ],
    stages: [
      { id: "workload", title: "Define traffic and success", goal: "Prevent an artificial benchmark from choosing the system.", instructions: ["Create interactive, long-context, and reasoning task slices with realistic input/output lengths.", "Define p50/p95 time-to-first-token, inter-token latency, total latency, quality, and cost-per-success targets.", "Choose an open-loop arrival pattern and a peak/burst scenario."], checkpoint: "The workload describes distributions and percentiles, not one average prompt at concurrency one.", hint: "Include cancellations and maximum output limits because they affect cache and queue capacity.", workspacePrompt: "Write the workload table, SLOs, arrival process, and why each slice matters." },
      { id: "memory", title: "Account for weights and cache", goal: "Show what fits before optimizing throughput.", instructions: ["Estimate weight memory at baseline and candidate quantization precisions including metadata.", "Estimate KV cache by layers, context, batch, KV heads, head width, and bytes; add runtime headroom.", "Measure peak memory and identify whether weights, cache, activations, or fragmentation dominate each slice."], checkpoint: "The maximum safe concurrency follows from measured headroom, not advertised GPU memory alone.", hint: "Grouped-query attention reduces KV heads; batch and context multiply cache usage.", workspacePrompt: "Show the memory equations, assumptions, measured peak, and safe headroom policy." },
      { id: "benchmark", title: "Run controlled serving tests", goal: "Separate quality, latency, throughput, and goodput trade-offs.", instructions: ["Compare at least two precisions and two batching/scheduler settings under identical requests.", "Compare deterministic versus sampled decoding where appropriate and one single-sample versus multi-sample reasoning policy.", "Report TTFT, inter-token latency, p95/p99, throughput, goodput, memory, errors, and task quality."], checkpoint: "Every comparison changes one named factor or explicitly documents interactions.", hint: "Warm the service, record seeds/settings, and distinguish cold model load from steady-state latency.", workspacePrompt: "Paste the benchmark matrix and identify the bottleneck in each workload slice." },
      { id: "policy", title: "Choose adaptive budgets and overload behavior", goal: "Turn benchmark results into an operable service policy.", instructions: ["Route easy requests to one sample and uncertain/high-value requests to more candidates or verification.", "Set bounded queues, admission limits, token/tool budgets, early stopping, and a cheaper fallback.", "Write the chosen configuration and a load-test condition that triggers scale, degrade, or reject."], checkpoint: "The policy maximizes SLO-satisfying goodput and fails predictably under overload.", hint: "A server at 100% utilization can deliver less goodput if tail latency causes most requests to miss the SLO.", workspacePrompt: "Write the routing, budget, admission, fallback, and scaling rules with supporting measurements." },
    ],
    rubric: [
      { criterion: "Workload realism", developing: "Uses one prompt and averages.", proficient: "Uses distributions, slices, percentiles, and bursts.", excellent: "Connects every slice to a user outcome and failure cost." },
      { criterion: "Resource model", developing: "Counts only weight file size.", proficient: "Includes KV cache, runtime, and headroom.", excellent: "Reconciles estimates with measured peaks and explains the gap." },
      { criterion: "Benchmark quality", developing: "Reports tokens/second only.", proficient: "Measures quality, latency, goodput, cost, and memory.", excellent: "Uses controlled factors, uncertainty, and end-to-end bottleneck attribution." },
      { criterion: "Operational decision", developing: "Picks the fastest setting.", proficient: "Chooses an SLO-aware configuration and overload policy.", excellent: "Uses adaptive budgets, rollback triggers, and value-per-compute evidence." },
    ],
    exemplar: { title: "An SLO-aware result", summary: "A 4-bit configuration fits more cache but is slower than optimized 8-bit at small batch, so 8-bit is selected. Continuous batching increases throughput while a decode-priority budget protects p95 inter-token latency. Exact tasks get one deterministic attempt; uncertain reasoning tasks get up to four samples plus a verifier. Admission control rejects work before the queue exceeds the first-token SLO.", decisions: ["Optimized goodput rather than saturated throughput.", "Measured quantization on target hardware instead of inferring from bit width.", "Allocated test-time compute only where a deployable verifier improved selection."] },
    reflection: ["Which performance metric changed your initial architecture choice?", "When did extra reasoning compute stop producing enough value?", "How would a different traffic mix invalidate your capacity recommendation?"],
  },

  "observability-governance": {
    lessonId: "observability-governance",
    title: "Ship a source-grounded research agent safely",
    outcome: "Produce a working or fully specified research-agent prototype with grounded citations, bounded tools, stage-level evaluations, privacy-aware traces, and a launch playbook.",
    estimatedTime: "6–10 hours",
    prerequisites: ["Context engineering", "RAG", "Agent loops", "Evaluation design", "Security and privacy", "Observability and governance"],
    materials: ["A small versioned document corpus", "Search/retrieval and one read-only tool", "A trace store with redaction", "An evaluation set including attacks"],
    deliverables: [
      { title: "Agent prototype/specification", description: "Context, retrieval, state machine, tools, citations, and termination." },
      { title: "Evaluation and threat report", description: "Stage metrics, end-to-end quality, adversarial tests, privacy findings, and cost." },
      { title: "Operations playbook", description: "Traces, SLOs, alerts, owners, canary, rollback, and incident response." },
    ],
    stages: [
      { id: "contract", title: "Define authority and success", goal: "Separate the user’s goal, trusted policy, untrusted evidence, and allowed effects.", instructions: ["Choose a bounded research domain and define answer quality, citation support, latency, and cost.", "Draw trust boundaries around user input, documents, model, retrieval, tools, secrets, and external services.", "Limit tools to read-only search/fetch initially; define termination and when to ask a human."], checkpoint: "No document or model output can grant itself permission, and success has observable criteria.", hint: "Start with less autonomy: a fixed retrieval workflow is valid if dynamic tool choice is unnecessary.", workspacePrompt: "Write the user contract, trust-boundary list, tools/scopes, success metrics, and stop conditions." },
      { id: "pipeline", title: "Build context, retrieval, and the loop", goal: "Make evidence flow reproducible and attributable.", instructions: ["Ingest versioned chunks with source IDs, dates, permissions, and document-level splits.", "Use hybrid retrieval or justify one method; rerank, enforce filters, and fit evidence into a token budget.", "Implement observe → propose → validate → execute → record → stop, with idempotency and repeated-action detection."], checkpoint: "Every answer claim can be mapped to a retrieved source version and every tool action to an authorized trace span.", hint: "Store structured state; do not rely on an ever-growing conversation transcript as the database.", workspacePrompt: "Document the chunking, retrieval, state, action validation, retry, citation, and termination design." },
      { id: "evaluate", title: "Evaluate stages and attack boundaries", goal: "Know whether failure begins in retrieval, generation, tools, or authorization.", instructions: ["Measure retrieval recall/ranking, answer correctness, citation entailment/completeness, abstention, tool validity, latency, and cost.", "Add indirect prompt injection, cross-tenant requests, forged tool output, missing evidence, stale sources, and loop/cost attacks.", "Calibrate any LLM judge against human labels and keep deterministic checks for schemas, permissions, and citations."], checkpoint: "The report contains raw examples and separate stage metrics, including both unsafe compliance and benign over-blocking.", hint: "Use oracle-context tests to separate retrieval from generation bottlenecks.", workspacePrompt: "Build the evaluation table, attack outcomes, judge calibration, and three prioritized failures." },
      { id: "operate", title: "Instrument, launch, and recover", goal: "Make change and failure accountable.", instructions: ["Trace prompt/model/index/tool versions, tokens, latency spans, decisions, errors, and costs with data minimization/redaction.", "Define SLOs, quality/safety release gates, alerts with owners, canary traffic, budgets, and a tested rollback.", "Write an incident drill for citation fabrication, data exposure, runaway cost, or tool compromise; convert the drill into regression tests."], checkpoint: "A new operator can detect, contain, reproduce, communicate, and prevent the chosen incident.", hint: "Every alert needs an owner and an action; every rollback needs versioned artifacts to restore.", workspacePrompt: "Write the trace schema, dashboards, gates, canary/rollback steps, and one incident runbook." },
    ],
    rubric: [
      { criterion: "Grounded architecture", developing: "Answers use unversioned context with weak citations.", proficient: "Evidence has provenance and stage boundaries are explicit.", excellent: "Retrieval/generation failures are independently diagnosable and reproducible." },
      { criterion: "Security and privacy", developing: "Relies on prompt instructions.", proficient: "Uses scoped access, validation, sandboxing, and minimized logs.", excellent: "Demonstrates adversarial tests, containment, and cross-tenant isolation." },
      { criterion: "Evaluation", developing: "Shows a few good answers.", proficient: "Measures stages, end-to-end success, slices, safety, and cost.", excellent: "Calibrates judges, uses uncertainty, and turns failures into gates." },
      { criterion: "Operations", developing: "Has dashboards without response rules.", proficient: "Defines SLOs, owners, canary, rollback, and incident steps.", excellent: "Rehearses recovery and traces decisions with privacy-aware evidence." },
    ],
    exemplar: { title: "A bounded, operable research assistant", summary: "A read-only policy assistant retrieves only the authenticated tenant’s versioned documents, uses a two-step search/read workflow, and refuses unsupported conclusions. The runtime blocks instructions inside documents, validates citations, caps tool calls, and traces stage versions with redaction. Release requires retrieval recall, citation entailment, answer quality, injection resistance, p95 latency, and cost gates; a canary can roll back model, prompt, and index together.", decisions: ["Kept tools read-only until the system proved value and reliability.", "Separated retrieval recall from grounded generation so teams know what to fix.", "Designed logs around incident questions while minimizing sensitive content."] },
    reflection: ["Which control prevents the highest-severity failure even if model behavior regresses?", "Which metric is an alerting proxy and which directly measures user success?", "What would you need to change before allowing the agent to perform write actions?"],
  },

  "interpretability-editing": {
    lessonId: "interpretability-editing",
    title: "Investigate and intervene on a false model claim",
    outcome: "Produce a causal investigation and intervention memo that chooses among retrieval correction, behavioral adaptation, activation/weight editing, and stronger deletion claims.",
    estimatedTime: "4–7 hours",
    prerequisites: ["Attention and residual streams", "Layers of understanding", "Evaluation design", "Interpretability and model editing"],
    materials: ["A small open Transformer with activation access", "A false-claim prompt set plus matched controls", "Optional interpretability library", "A results notebook"],
    deliverables: [
      { title: "Claim and behavior map", description: "Target prompts, paraphrases, related facts, controls, and baseline probabilities." },
      { title: "Causal evidence report", description: "Localization method, intervention, controls, results, and alternative explanations." },
      { title: "Intervention decision", description: "Chosen remedy with efficacy, locality, durability, and operations plan." },
    ],
    stages: [
      { id: "scope", title: "Scope the claim", goal: "Make success and collateral damage measurable before looking inside the model.", instructions: ["Choose one reproducible false claim in an open small model and confirm it across paraphrases and decoding settings.", "Create related-fact prompts, unrelated controls, adversarial formulations, and a correct-evidence condition.", "Decide whether the operational need is current factuality, behavioral suppression, a weight change, or verified removal of training influence."], checkpoint: "The target, generalization set, locality set, and claim strength are all explicit.", hint: "If the fact changes frequently, retrieval correction may be more appropriate than editing weights.", workspacePrompt: "Write the target behavior, prompt sets, baseline metrics, intended claim, and unacceptable side effects." },
      { id: "observe", title: "Observe without overclaiming", goal: "Use correlational tools to generate a precise causal hypothesis.", instructions: ["Compare activations or attributions on clean/corrupted matched prompts at aligned tokens and layers.", "Optionally train a probe or inspect sparse features, using held-out data and controls for syntax/topic/length.", "State what is merely associated, what is decodable, and the component you predict is causally relevant."], checkpoint: "The hypothesis names an intervention and predicted output change; it does not call an attention map a complete explanation.", hint: "A probe may read information the forward computation never uses.", workspacePrompt: "Record the contrast, observational finding, confound controls, and causal prediction." },
      { id: "intervene", title: "Test causality", goal: "Change an internal state and measure a controlled behavioral consequence.", instructions: ["Patch clean activations into a corrupted run or ablate/steer the nominated component.", "Measure target-logit change and behavioral success across paraphrases, related facts, and unrelated controls.", "Repeat at neighboring layers/positions and with sham interventions to estimate specificity."], checkpoint: "The effect is repeatable, directionally predicted, and stronger at the nominated site than matched controls.", hint: "One successful patch can show sufficiency for that run without proving the model stores the fact in one human-readable location.", workspacePrompt: "Describe the intervention, controls, effect sizes, null results, and the strongest defensible causal claim." },
      { id: "choose", title: "Choose and audit the intervention", goal: "Select the least invasive remedy that meets the actual operational goal.", instructions: ["Compare retrieval update, prompt/runtime guard, LoRA/behavioral tuning, activation steering, and targeted weight editing.", "For any edit, measure efficacy, paraphrase transfer, related/unrelated locality, robustness, persistence, calibration, and broad regression.", "If claiming unlearning, define the threat model and evidence beyond refusal or suppression; otherwise use narrower language."], checkpoint: "The memo explains why the selected intervention’s evidence and blast radius match the goal.", hint: "A successful factual edit does not prove the original training datum is unrecoverable.", workspacePrompt: "Write the option table, selected remedy, evaluation results/plan, rollback, and exact wording of the claim you can support." },
    ],
    rubric: [
      { criterion: "Claim discipline", developing: "Conflates attention, probes, causality, and deletion.", proficient: "Labels correlational, decodable, causal, and editing evidence correctly.", excellent: "Matches every conclusion to controls and a stated threat model." },
      { criterion: "Experimental design", developing: "Uses one prompt without controls.", proficient: "Uses matched contrasts, interventions, paraphrases, and locality sets.", excellent: "Adds sham/neighbor interventions, effect sizes, and alternative hypotheses." },
      { criterion: "Intervention choice", developing: "Edits weights by default.", proficient: "Compares retrieval, runtime, adapter, activation, and weight options.", excellent: "Chooses the least invasive remedy with operational rollback." },
      { criterion: "Side-effect evaluation", developing: "Checks target efficacy only.", proficient: "Measures generalization, locality, robustness, and persistence.", excellent: "Includes calibration, broad regressions, adversarial recovery, and long-term maintenance." },
    ],
    exemplar: { title: "A defensible outcome", summary: "Matched activation patching identifies a mid-layer site that causally shifts the false completion, but effects are distributed and not perfectly local. Because the policy fact changes over time, the team chooses versioned retrieval with citation validation rather than a permanent weight edit. A small adapter is reserved for response behavior. The memo explicitly declines to claim unlearning because no training-influence threat model was tested.", decisions: ["Used internal analysis to understand behavior, not to force a weight-edit conclusion.", "Selected retrieval because the operational truth is time-varying and auditable.", "Reported causal sufficiency for tested prompts without claiming a complete mechanism."] },
    reflection: ["What evidence most constrained the strength of your interpretability claim?", "Which nearby behavior was most at risk from the intervention?", "What additional test would be required before using the word ‘unlearned’?"],
  },
};
