export type LessonCodeExample = {
  title: string;
  language: string;
  setup: string;
  predict: string;
  code: string;
  observe: string;
  tryIt: string;
  caveat?: string;
};

const lines = (...values: string[]) => values.join("\n");

export const lessonCodeExamples: Record<string, LessonCodeExample> = {
  introduction: {
    title: "See the autoregressive loop",
    language: "Python-like pseudocode",
    setup: "The model performs one operation repeatedly: score the next token, choose one, append it, and run again.",
    predict: "Which line makes generation sequential even though training can process many positions together?",
    code: lines(
      "tokens = tokenizer.encode(prompt)",
      "for _ in range(max_new_tokens):",
      "    logits = model(tokens)",
      "    next_id = sample(logits[-1], temperature=0.8)",
      "    tokens.append(next_id)",
      "    if next_id == tokenizer.eos_id:",
      "        break",
      "print(tokenizer.decode(tokens))"
    ),
    observe: "Each new model call depends on the token selected by the previous call. The loop—not a hidden chat database—constructs the continuation.",
    tryIt: "Replace sample with argmax. Predict how reproducibility and diversity change.",
    caveat: "Interface names are illustrative; real tokenizers batch tensors and real models also manage positions and a KV cache.",
  },
  "tensors-shapes": {
    title: "Make the shape contract executable",
    language: "Python · NumPy",
    setup: "A projection changes feature width while preserving batch and token axes.",
    predict: "What shape will Y have, and which axis disappears during multiplication?",
    code: lines(
      "import numpy as np",
      "",
      "B, T, d, out = 2, 3, 4, 6",
      "X = np.random.randn(B, T, d)",
      "W = np.random.randn(d, out)",
      "Y = X @ W",
      "",
      "print(X.shape, W.shape, Y.shape)",
      "assert Y.shape == (B, T, out)"
    ),
    observe: "NumPy contracts the shared d axis independently at every B,T position, returning [2,3,6].",
    tryIt: "Transpose W and read the error. Explain it using named axes before fixing it.",
  },
  "probability-softmax": {
    title: "Implement stable softmax and target loss",
    language: "Python · NumPy",
    setup: "Subtracting the maximum prevents overflow without changing relative probabilities.",
    predict: "Will adding 1000 to every logit change the probabilities?",
    code: lines(
      "import numpy as np",
      "",
      "z = np.array([2.0, 1.0, 0.0])",
      "stable = z - z.max()",
      "p = np.exp(stable) / np.exp(stable).sum()",
      "target = 2",
      "loss = -np.log(p[target])",
      "",
      "print(p.round(3), round(loss, 3))"
    ),
    observe: "The probabilities sum to one. A low target probability creates a large negative-log loss.",
    tryIt: "Run the same calculation with z + 1000, then multiply z by 2 and compare the two outcomes.",
  },
  "gradients-backprop": {
    title: "Let autograd expose the chain rule",
    language: "Python · PyTorch",
    setup: "One scalar loss can send a derivative back to every contributing parameter.",
    predict: "For w=2, x=3, and target=5, is the gradient positive or negative?",
    code: lines(
      "import torch",
      "",
      "w = torch.tensor(2.0, requires_grad=True)",
      "x, target = torch.tensor(3.0), torch.tensor(5.0)",
      "prediction = w * x",
      "loss = (prediction - target) ** 2",
      "loss.backward()",
      "",
      "print('loss:', loss.item(), 'dL/dw:', w.grad.item())"
    ),
    observe: "The gradient is +6: increasing w locally increases the already-too-large prediction and therefore the loss.",
    tryIt: "Change the target to 7. Predict the gradient sign before running.",
  },
  optimizers: {
    title: "Separate gradient computation from the update rule",
    language: "Python · PyTorch",
    setup: "Backprop fills w.grad; the optimizer decides how that gradient changes w.",
    predict: "Does one small SGD step move w toward or away from the optimum 5/3?",
    code: lines(
      "import torch",
      "",
      "w = torch.tensor(2.0, requires_grad=True)",
      "optimizer = torch.optim.SGD([w], lr=0.05)",
      "loss = (w * 3.0 - 5.0) ** 2",
      "optimizer.zero_grad()",
      "loss.backward()",
      "optimizer.step()",
      "",
      "print(w.item())"
    ),
    observe: "Backprop and optimization are distinct stages. The learning rate controls how far the optimizer trusts the local slope.",
    tryIt: "Increase lr to 0.5 and compare the new loss after the step. Look for overshoot.",
  },
  tokenization: {
    title: "Inspect text as bytes before subwords",
    language: "Python · standard library",
    setup: "Modern tokenizers ultimately need a reversible representation of Unicode text.",
    predict: "Will the emoji occupy one byte or several UTF-8 bytes?",
    code: lines(
      "text = 'LLMs 🤖'",
      "raw = text.encode('utf-8')",
      "",
      "print(list(raw))",
      "print('characters:', len(text))",
      "print('bytes:', len(raw))",
      "assert raw.decode('utf-8') == text"
    ),
    observe: "Characters and bytes are different units. Byte-level tokenizers guarantee coverage, while learned merges compress common byte sequences.",
    tryIt: "Compare an accented character written directly with the same visible character built from a letter plus combining mark.",
  },
  "embedding-layer": {
    title: "Turn arbitrary IDs into learned vectors",
    language: "Python · PyTorch",
    setup: "An embedding lookup selects rows; it does not calculate meaning from the integer value of an ID.",
    predict: "Will repeated token ID 2 begin with the same vector at both positions?",
    code: lines(
      "import torch",
      "",
      "table = torch.nn.Embedding(num_embeddings=5, embedding_dim=3)",
      "ids = torch.tensor([[2, 0, 2]])",
      "vectors = table(ids)",
      "",
      "print(vectors.shape)",
      "print(torch.equal(vectors[0, 0], vectors[0, 2]))"
    ),
    observe: "The lookup returns [B,T,d], and equal IDs select equal initial rows before contextual layers mix information.",
    tryIt: "Swap the numeric labels for two vocabulary items without moving their rows. Explain why ID size has no semantic order.",
  },
  "positional-encoding": {
    title: "Rotate one RoPE coordinate pair",
    language: "Python · NumPy",
    setup: "RoPE makes position affect query/key geometry by rotating pairs of coordinates.",
    predict: "Does rotation preserve the vector length?",
    code: lines(
      "import numpy as np",
      "",
      "v = np.array([1.0, 0.0])",
      "position, frequency = 3, 0.4",
      "angle = position * frequency",
      "R = np.array([[np.cos(angle), -np.sin(angle)],",
      "              [np.sin(angle),  np.cos(angle)]])",
      "rotated = R @ v",
      "print(rotated, np.linalg.norm(rotated))"
    ),
    observe: "Position changes direction while preserving magnitude. Real RoPE applies different frequencies to many coordinate pairs.",
    tryIt: "Compare dot products between positions 2 and 3, then positions 2 and 20.",
  },
  attention: {
    title: "Build one causal attention head",
    language: "Python · PyTorch",
    setup: "The mechanism is score → scale → causal mask → softmax → weighted values.",
    predict: "Which entries in the first query row must have zero probability?",
    code: lines(
      "import torch",
      "",
      "Q = K = V = torch.randn(1, 4, 8)",
      "scores = Q @ K.transpose(-2, -1) / (8 ** 0.5)",
      "future = torch.triu(torch.ones(4, 4, dtype=torch.bool), diagonal=1)",
      "scores = scores.masked_fill(future, float('-inf'))",
      "weights = scores.softmax(dim=-1)",
      "output = weights @ V",
      "print(weights[0].round(decimals=2), output.shape)"
    ),
    observe: "Future positions receive exactly zero weight after masking and normalization; the output preserves [B,T,d].",
    tryIt: "Move masking after softmax and explain why simply zeroing future weights no longer leaves rows normalized.",
  },
  "layers-of-understanding": {
    title: "Write the residual block contract",
    language: "Python · PyTorch",
    setup: "Attention and the MLP must return the residual width so their updates can be added.",
    predict: "Which assertion fails if the MLP returns 2d instead of d?",
    code: lines(
      "def transformer_block(x, norm1, attention, norm2, mlp):",
      "    attention_update = attention(norm1(x))",
      "    assert attention_update.shape == x.shape",
      "    h = x + attention_update",
      "    mlp_update = mlp(norm2(h))",
      "    assert mlp_update.shape == h.shape",
      "    return h + mlp_update"
    ),
    observe: "The residual stream is a stable interface. Sublayers may expand internally but project back before addition.",
    tryIt: "Add hooks that print the norm of x and each update. Look for one branch dominating the stream.",
  },
  "learning-to-predict": {
    title: "Align logits with next-token targets",
    language: "Python · PyTorch",
    setup: "The model output at position t is scored against token t+1.",
    predict: "If a sequence has T tokens, how many adjacent prediction targets does it supply?",
    code: lines(
      "import torch.nn.functional as F",
      "",
      "# logits: [B,T,V], token_ids: [B,T]",
      "prediction_logits = logits[:, :-1, :]",
      "next_ids = token_ids[:, 1:]",
      "loss = F.cross_entropy(",
      "    prediction_logits.reshape(-1, prediction_logits.size(-1)),",
      "    next_ids.reshape(-1)",
      ")"
    ),
    observe: "Both tensors now cover T-1 aligned positions. An off-by-one error can silently train copying instead of prediction.",
    tryIt: "Print the decoded input token and target token for three positions before trusting the batch pipeline.",
  },
  "gpt2-from-scratch": {
    title: "Trace the tiny GPT shape spine",
    language: "Python · PyTorch",
    setup: "A few assertions can turn an architecture diagram into a debuggable contract.",
    predict: "Which layer is the first to expose vocabulary size V?",
    code: lines(
      "B, T, d, V = 2, 16, 64, 1000",
      "x = token_embedding(token_ids) + position_embedding[:T]",
      "assert x.shape == (B, T, d)",
      "for block in blocks:",
      "    x = block(x)",
      "    assert x.shape == (B, T, d)",
      "logits = language_model_head(final_norm(x))",
      "assert logits.shape == (B, T, V)"
    ),
    observe: "The residual width stays fixed across blocks. Only the vocabulary head changes the final axis from d to V.",
    tryIt: "Add the shifted-loss snippet from the previous lesson and overfit one tiny batch.",
  },
  "pretraining-overview": {
    title: "Read one optimizer step as a pipeline",
    language: "Python · PyTorch-style pseudocode",
    setup: "Pre-training is a repeated, observable systems pipeline rather than one call to train.",
    predict: "Which state must be checkpointed besides model weights to resume faithfully?",
    code: lines(
      "for batch in loader:",
      "    optimizer.zero_grad()",
      "    logits = model(batch.input_ids)",
      "    loss = shifted_cross_entropy(logits, batch.input_ids)",
      "    loss.backward()",
      "    clip_grad_norm_(model.parameters(), max_norm=1.0)",
      "    optimizer.step()",
      "    scheduler.step()",
      "    log(loss=loss, tokens=batch.num_tokens)"
    ),
    observe: "Data, loss alignment, gradients, optimizer, schedule, and telemetry all participate in one step.",
    tryIt: "List the model, optimizer, scheduler, RNG, and data-position state required in a resumable checkpoint.",
  },
  "objectives-details": {
    title: "Construct causal targets and a loss mask",
    language: "Python · PyTorch",
    setup: "Target alignment and masking jointly define which predictions count.",
    predict: "What value should padded or excluded targets use?",
    code: lines(
      "import torch",
      "",
      "ids = torch.tensor([[10, 20, 30, 0, 0]])",
      "inputs = ids[:, :-1]",
      "targets = ids[:, 1:].clone()",
      "targets[targets == 0] = -100",
      "",
      "print(inputs)",
      "print(targets)  # -100 is ignored by CrossEntropyLoss"
    ),
    observe: "The sequence shift supplies next-token labels; ignore indices prevent artificial padding from changing the objective.",
    tryIt: "Create two packed documents and decide whether the boundary transition should carry loss.",
  },
  "scaling-laws": {
    title: "Compare equal-compute allocations",
    language: "Python · standard library",
    setup: "A crude dense-training proxy helps reject impossible plans before pilots choose the best one.",
    predict: "Do equal values of 6ND imply equal quality or serving cost?",
    code: lines(
      "plans = {",
      "    'smaller_more_data': {'N': 1e9, 'D': 20e9},",
      "    'larger_less_data': {'N': 2e9, 'D': 10e9},",
      "}",
      "for name, plan in plans.items():",
      "    flops = 6 * plan['N'] * plan['D']",
      "    print(name, f'{flops:.2e} FLOPs')"
    ),
    observe: "The proxy is equal, but memory, data exposure, capacity, optimization, and downstream quality differ.",
    tryIt: "Add a memory constraint and eliminate plans that cannot train or serve on the target hardware.",
  },
  "data-engineering": {
    title: "Split documents before making windows",
    language: "Python · standard library",
    setup: "A correct split prevents neighboring chunks from one document leaking into train and validation.",
    predict: "Why is shuffling windows before splitting unsafe?",
    code: lines(
      "import hashlib",
      "",
      "def split_for(document_id):",
      "    bucket = int(hashlib.sha256(document_id.encode()).hexdigest(), 16) % 100",
      "    return 'train' if bucket < 90 else 'validation'",
      "",
      "for document in documents:",
      "    split = split_for(document.id)",
      "    write_windows(split, tokenize(document.text))"
    ),
    observe: "Every window from one document follows the same deterministic split, making reruns auditable.",
    tryIt: "Add exact-content hashes and count duplicates that cross sources or splits.",
  },
  infrastructure: {
    title: "See gradient accumulation versus synchronization",
    language: "Python · distributed pseudocode",
    setup: "Microbatches reduce activation memory; distributed workers must still agree on the global update.",
    predict: "When should gradients be synchronized if four microbatches form one optimizer step?",
    code: lines(
      "optimizer.zero_grad()",
      "for microbatch in microbatches:",
      "    with model.no_sync_until_last_microbatch():",
      "        loss = model(microbatch) / len(microbatches)",
      "        loss.backward()",
      "all_reduce_gradients(model.parameters())",
      "clip_grad_norm_(model.parameters(), 1.0)",
      "optimizer.step()"
    ),
    observe: "Accumulation changes when activations are resident; sharding and all-reduce change where parameters, states, and communication live.",
    tryIt: "Draw which bytes are replicated or sharded under data parallelism versus FSDP.",
    caveat: "Frameworks expose different synchronization contexts; this is a communication sketch, not copy-paste distributed code.",
  },
  "advanced-objectives": {
    title: "Serialize a fill-in-the-middle example",
    language: "Python · standard library",
    setup: "FIM changes input order while retaining ordinary causal next-token training.",
    predict: "Which portion becomes the continuation target after the special MID token?",
    code: lines(
      "prefix = 'def area(r):'",
      "middle = ' return 3.14 * r * r'",
      "suffix = '\\nprint(area(2))'",
      "",
      "sample = '<PRE>' + prefix + '<SUF>' + suffix + '<MID>' + middle",
      "tokens = tokenizer.encode(sample)",
      "inputs, targets = tokens[:-1], tokens[1:]"
    ),
    observe: "The missing middle appears late in the serialized causal sequence, so left-to-right loss can teach insertion.",
    tryIt: "Vary the mixture percentage of FIM samples and name the left-to-right capability you would monitor for regression.",
  },
  "pretraining-evaluation": {
    title: "Compute perplexity from token losses",
    language: "Python · NumPy",
    setup: "Perplexity exponentiates mean negative log-likelihood on one fixed data/tokenization protocol.",
    predict: "Can you compare perplexities from different tokenizers as if they used the same unit?",
    code: lines(
      "import numpy as np",
      "",
      "token_nll = np.array([1.8, 2.1, 2.0, 2.2])",
      "mean_nll = token_nll.mean()",
      "perplexity = np.exp(mean_nll)",
      "print(round(mean_nll, 3), round(perplexity, 3))"
    ),
    observe: "Perplexity is a dense objective-fit signal, not a complete capability or safety score.",
    tryIt: "Plot train and validation NLL together and mark a synthetic loss spike.",
  },
  sft: {
    title: "Mask loss to assistant tokens",
    language: "Python · PyTorch-style pseudocode",
    setup: "The prompt remains visible context while excluded positions receive no supervised loss.",
    predict: "Should system and user tokens be deleted from the input or only masked from the target loss?",
    code: lines(
      "tokens, roles = render_chat(conversation)",
      "labels = tokens.clone()",
      "labels[roles != 'assistant'] = -100",
      "",
      "logits = model(tokens)",
      "loss = cross_entropy(logits[:, :-1], labels[:, 1:], ignore_index=-100)"
    ),
    observe: "Assistant-only masking changes what is imitated without hiding the prompt from the forward pass.",
    tryIt: "Inspect three rendered examples around role boundaries and verify the first assistant token has the intended target.",
  },
  "preference-optimization": {
    title: "Read the core DPO comparison",
    language: "Python · PyTorch",
    setup: "DPO compares how much the policy favors chosen over rejected responses relative to a reference.",
    predict: "What happens to the loss when the policy increases the chosen/rejected log-probability gap?",
    code: lines(
      "import torch.nn.functional as F",
      "",
      "policy_gap = chosen_logp - rejected_logp",
      "reference_gap = ref_chosen_logp - ref_rejected_logp",
      "advantage = beta * (policy_gap - reference_gap)",
      "loss = -F.logsigmoid(advantage).mean()"
    ),
    observe: "The objective rewards relative preference while the reference anchors how far the policy moves.",
    tryIt: "Add a pair where chosen and rejected differ only in length; inspect whether the dataset encodes a length shortcut.",
  },
  "rl-fundamentals": {
    title: "Turn an advantage into a policy gradient",
    language: "Python · PyTorch",
    setup: "Actions with above-baseline return should become more likely.",
    predict: "What sign does the loss have when advantage is positive and log-probability is negative?",
    code: lines(
      "action = policy.sample(state)",
      "log_probability = policy.log_prob(action, state)",
      "return_value = environment.reward(action)",
      "advantage = return_value - value_baseline(state)",
      "",
      "policy_loss = -(log_probability * advantage)",
      "policy_loss.backward()"
    ),
    observe: "Gradient descent on the negative objective increases probability for positive-advantage samples and decreases it for negative ones.",
    tryIt: "Use a batch mean baseline and compare the variance of updates across repeated samples.",
  },
  rlhf: {
    title: "Combine learned reward with KL control",
    language: "Python · RL pseudocode",
    setup: "Classic RLHF balances reward-model preference against drift from a reference policy.",
    predict: "Can a response with higher raw reward receive lower total objective value?",
    code: lines(
      "response = policy.generate(prompt)",
      "reward = reward_model(prompt, response)",
      "logp = policy.log_prob(response, prompt)",
      "ref_logp = reference.log_prob(response, prompt)",
      "kl_estimate = logp - ref_logp",
      "objective = reward - beta * kl_estimate",
      "ppo_update(policy, objective)"
    ),
    observe: "A large reference-policy departure can outweigh reward gain, constraining destructive reward chasing.",
    tryIt: "Track reward, KL, response length, and held-out human preference separately during a toy run.",
    caveat: "Production PPO uses token-level ratios, clipping, value estimation, and batching details omitted here.",
  },
  "tools-safety": {
    title: "Keep runtime authority outside the model",
    language: "Python-like pseudocode",
    setup: "A model may propose a typed call; deterministic code validates schema, scope, and confirmation.",
    predict: "Which check prevents text inside a webpage from granting a purchase capability?",
    code: lines(
      "proposal = model.propose_tool_call(context)",
      "call = validate_schema(proposal, tool_registry)",
      "require_capability(user, call.tool, call.scope)",
      "if call.has_side_effect:",
      "    require_user_confirmation(call.summary)",
      "result = sandbox.execute(call, timeout=10)",
      "return validate_tool_result(result)"
    ),
    observe: "The model chooses a candidate action, but code owns permission, validation, execution, and result handling.",
    tryIt: "Add an indirect prompt-injection string to a tool result and verify that it cannot alter the capability check.",
  },
  "decoding-sampling": {
    title: "Implement nucleus sampling",
    language: "Python · NumPy",
    setup: "Top-p retains the smallest highest-probability set reaching a cumulative threshold.",
    predict: "For probabilities [0.50,0.25,0.15,0.07,0.03] and p=0.8, how many tokens remain?",
    code: lines(
      "import numpy as np",
      "",
      "probabilities = np.array([.50, .25, .15, .07, .03])",
      "order = np.argsort(probabilities)[::-1]",
      "cumulative = np.cumsum(probabilities[order])",
      "keep_count = np.searchsorted(cumulative, .8) + 1",
      "keep = order[:keep_count]",
      "renormalized = probabilities[keep] / probabilities[keep].sum()",
      "print(keep, renormalized)"
    ),
    observe: "Three tokens remain because the first two total 0.75 and the third crosses 0.8.",
    tryIt: "Change the distribution to nearly uniform and observe how nucleus size adapts.",
  },
  "generation-kv-cache": {
    title: "Estimate KV-cache memory",
    language: "Python · standard library",
    setup: "Cache memory grows linearly with layers, sequence length, KV heads, head width, bytes, and concurrency.",
    predict: "Which model change reduces cache memory without shortening context?",
    code: lines(
      "def kv_cache_gib(layers, tokens, kv_heads, head_dim, bytes_per_value, batch=1):",
      "    elements = 2 * layers * tokens * kv_heads * head_dim * batch",
      "    return elements * bytes_per_value / (1024 ** 3)",
      "",
      "print(kv_cache_gib(",
      "    layers=32, tokens=8192, kv_heads=8, head_dim=128,",
      "    bytes_per_value=2, batch=1",
      "))"
    ),
    observe: "The factor two stores both keys and values. Grouped-query attention lowers kv_heads.",
    tryIt: "Compute safe concurrency after reserving weight and runtime headroom on an 80 GiB GPU.",
  },
  "quantization-memory": {
    title: "Quantize and reconstruct a vector",
    language: "Python · NumPy",
    setup: "Symmetric quantization chooses a scale, rounds to integer levels, then approximately reconstructs values.",
    predict: "Which values experience the largest reconstruction error?",
    code: lines(
      "import numpy as np",
      "",
      "x = np.array([-1.0, -0.2, 0.3, 0.9])",
      "qmax = 3  # signed 3-bit positive range",
      "scale = np.abs(x).max() / qmax",
      "q = np.clip(np.round(x / scale), -4, 3).astype(int)",
      "x_hat = q * scale",
      "print(q, x_hat.round(3), np.abs(x - x_hat).round(3))"
    ),
    observe: "A shared scale preserves the extremes but coarsens smaller values. Granularity and outliers matter.",
    tryIt: "Add a value of 10 and see how one outlier reduces resolution for all other values.",
  },
  "serving-systems": {
    title: "Measure goodput, not only throughput",
    language: "Python · standard library",
    setup: "Goodput counts only successful requests that satisfy the service-level objective.",
    predict: "Can a configuration have higher throughput but lower goodput?",
    code: lines(
      "requests = [",
      "    {'latency_ms': 420, 'correct': True},",
      "    {'latency_ms': 900, 'correct': True},",
      "    {'latency_ms': 380, 'correct': False},",
      "    {'latency_ms': 510, 'correct': True},",
      "]",
      "slo_ms = 600",
      "good = [r for r in requests if r['correct'] and r['latency_ms'] <= slo_ms]",
      "print('throughput:', len(requests), 'goodput:', len(good))"
    ),
    observe: "Only two of four completions are useful under the chosen quality and latency contract.",
    tryIt: "Compare two batching policies using p95 latency and goodput rather than average tokens per second alone.",
  },
  "test-time-compute": {
    title: "Select among candidates with a verifier",
    language: "Python-like pseudocode",
    setup: "Additional samples create value only when they add useful diversity and selection is reliable.",
    predict: "What happens if all candidates are identical or the verifier is random?",
    code: lines(
      "candidates = [model.solve(problem, seed=s) for s in range(8)]",
      "checked = []",
      "for candidate in candidates:",
      "    score = verifier(problem, candidate)",
      "    checked.append((score, candidate))",
      "best_score, best = max(checked, key=lambda item: item[0])",
      "return best if best_score >= acceptance_threshold else abstain()"
    ),
    observe: "More generation is not synonymous with more correctness. Candidate diversity and verifier validity are separate bottlenecks.",
    tryIt: "Hold total tokens fixed and compare one long attempt with four shorter attempts.",
  },
  "context-engineering": {
    title: "Assemble context under an explicit budget",
    language: "Python-like pseudocode",
    setup: "Context is a scarce, ordered interface containing authority, evidence, examples, and task state.",
    predict: "Which blocks should be dropped first when the budget is exceeded?",
    code: lines(
      "blocks = [system_policy, user_request, trusted_evidence, examples, history]",
      "context = []",
      "remaining = token_budget",
      "for block in prioritize(blocks):",
      "    if block.tokens <= remaining:",
      "        context.append(tag_with_provenance(block))",
      "        remaining -= block.tokens",
      "return render(context)"
    ),
    observe: "Selection and ordering are program decisions. More context can add distraction, cost, and attack surface.",
    tryIt: "Define a priority rule that never drops system policy but trims redundant history before trusted evidence.",
  },
  rag: {
    title: "Retrieve by cosine similarity",
    language: "Python · NumPy",
    setup: "A minimal retriever embeds the query and ranks chunk vectors before generation sees evidence.",
    predict: "Does high vector similarity prove that a chunk supports the final claim?",
    code: lines(
      "import numpy as np",
      "",
      "def cosine(a, b):",
      "    return a @ b / (np.linalg.norm(a) * np.linalg.norm(b))",
      "",
      "query_vector = embed(query)",
      "ranked = sorted(chunks, key=lambda c: cosine(query_vector, c.vector), reverse=True)",
      "evidence = ranked[:4]",
      "answer = generate_with_citations(query, evidence)"
    ),
    observe: "Retrieval proposes evidence; generation and citation checks must still verify entailment and coverage.",
    tryIt: "Add an oracle-context test to separate retrieval failure from generation failure.",
  },
  "agent-loops": {
    title: "Write a bounded agent state machine",
    language: "Python-like pseudocode",
    setup: "The orchestrator owns state, legal transitions, retry budgets, permissions, and termination.",
    predict: "Which branch prevents a failing tool from creating an infinite loop?",
    code: lines(
      "state = load_checkpoint()",
      "for step in range(MAX_STEPS):",
      "    proposal = model.propose(state)",
      "    action = validate_action(proposal, state.allowed_actions)",
      "    result = execute_with_idempotency(action)",
      "    state = record(state, action, result)",
      "    if result.is_terminal:",
      "        return verify_receipt(result)",
      "return stop('step budget exhausted')"
    ),
    observe: "The loop terminates by explicit success or budget. The transcript is not the sole source of state.",
    tryIt: "Add a retryable timeout, a non-retryable permission error, and a repeated-action detector.",
  },
  "evaluation-design": {
    title: "Expose regressions with slices",
    language: "Python · standard library",
    setup: "Averages can improve while a high-risk subgroup gets worse.",
    predict: "Which report would reveal a refund-policy regression hidden by overall accuracy?",
    code: lines(
      "from collections import defaultdict",
      "",
      "scores = defaultdict(list)",
      "for case in evaluation_set:",
      "    result = run_system(case.input)",
      "    scores[case.slice].append(score(case, result))",
      "",
      "for name, values in scores.items():",
      "    print(name, sum(values) / len(values), len(values))"
    ),
    observe: "Every aggregate needs inspectable slices, sample counts, scorer definitions, and uncertainty.",
    tryIt: "Add a paired comparison against the previous model and bootstrap a confidence interval.",
  },
  "security-privacy": {
    title: "Make authorization independent of text",
    language: "Python-like pseudocode",
    setup: "Instruction provenance and authenticated capability are different checks.",
    predict: "Can a tool result that says ADMIN=true change the authenticated principal?",
    code: lines(
      "def authorize(principal, action, content_source):",
      "    if content_source in {'web', 'document', 'tool_output'}:",
      "        mark_untrusted_data(content_source)",
      "    require_authenticated(principal)",
      "    require_scope(principal.capabilities, action.required_scope)",
      "    if action.is_consequential:",
      "        require_confirmation(principal, action)",
      "    return allow_with_audit_record(principal, action)"
    ),
    observe: "Text may influence a proposal but cannot mint identity, scope, or user confirmation.",
    tryIt: "Threat-model cross-tenant retrieval and verify that document text cannot alter the tenant filter.",
  },
  "observability-governance": {
    title: "Trace one request across stages",
    language: "Python-like pseudocode",
    setup: "A useful trace records enough linked evidence to localize quality, latency, cost, and safety failures.",
    predict: "Which span distinguishes retrieval latency from model-generation latency?",
    code: lines(
      "with trace('answer_request', privacy='redacted') as root:",
      "    evidence = span('retrieval', query_hash=query_hash).run(retrieve)",
      "    answer = span('generation', model=model_version).run(generate, evidence)",
      "    checked = span('validation', policy=policy_version).run(validate, answer)",
      "    root.metric('input_tokens', count_tokens(evidence))",
      "    root.metric('output_tokens', count_tokens(answer))",
      "    root.metric('cost_usd', estimate_cost(root))",
      "    return checked"
    ),
    observe: "Linked versions and spans support reproduction without requiring indiscriminate raw-prompt retention.",
    tryIt: "Assign an owner, threshold, and response playbook to one quality and one latency signal.",
  },
  distillation: {
    title: "Match softened teacher probabilities",
    language: "Python · PyTorch",
    setup: "Temperature exposes the teacher’s relative beliefs among non-target alternatives.",
    predict: "What happens to the teacher distribution as temperature increases?",
    code: lines(
      "import torch.nn.functional as F",
      "",
      "temperature = 2.0",
      "teacher_p = F.softmax(teacher_logits / temperature, dim=-1)",
      "student_logp = F.log_softmax(student_logits / temperature, dim=-1)",
      "distill_loss = F.kl_div(student_logp, teacher_p, reduction='batchmean')",
      "distill_loss = distill_loss * (temperature ** 2)"
    ),
    observe: "Higher temperature softens the target; the squared factor preserves gradient scale in the standard formulation.",
    tryIt: "Blend distillation loss with ground-truth cross-entropy and sweep the mixture weight.",
  },
  lora: {
    title: "Implement a low-rank update",
    language: "Python · PyTorch",
    setup: "The base weight remains frozen while two small factors learn an additive update.",
    predict: "How many trainable values replace a full d-by-d update at rank r?",
    code: lines(
      "import torch",
      "",
      "class LoRALinear(torch.nn.Module):",
      "    def __init__(self, base, rank=8, alpha=16):",
      "        super().__init__()",
      "        self.base = base.requires_grad_(False)",
      "        self.A = torch.nn.Parameter(torch.zeros(rank, base.in_features))",
      "        self.B = torch.nn.Parameter(torch.zeros(base.out_features, rank))",
      "        self.scale = alpha / rank",
      "    def forward(self, x):",
      "        return self.base(x) + self.scale * (x @ self.A.T @ self.B.T)"
    ),
    observe: "Trainable parameters scale with r(d_in+d_out), while the frozen base weight is still used and stored.",
    tryIt: "Print trainable parameter counts at ranks 4, 8, 16, and 64.",
  },
  moe: {
    title: "Route tokens to top-2 experts",
    language: "Python · PyTorch-style pseudocode",
    setup: "A router scores experts per token and activates only a sparse subset.",
    predict: "Why can one popular expert become a throughput bottleneck?",
    code: lines(
      "router_logits = router(hidden_states)        # [tokens, experts]",
      "top_values, top_ids = router_logits.topk(k=2, dim=-1)",
      "gates = top_values.softmax(dim=-1)",
      "output = zeros_like(hidden_states)",
      "for slot in range(2):",
      "    dispatched = dispatch(hidden_states, top_ids[:, slot], capacity)",
      "    output += gates[:, slot, None] * run_experts(dispatched)",
      "loss += load_balance_loss(router_logits)"
    ),
    observe: "Sparse FLOPs do not remove dispatch, capacity, communication, or load-balance costs.",
    tryIt: "Count tokens per expert for a skewed router and calculate how many exceed capacity.",
  },
  "multimodal-models": {
    title: "Turn an image into patch tokens",
    language: "Python · PyTorch",
    setup: "A vision encoder begins by partitioning pixels into fixed-size patches before projection.",
    predict: "How many patch tokens does a 224-by-224 image create with 16-by-16 patches?",
    code: lines(
      "import torch",
      "",
      "image = torch.randn(1, 3, 224, 224)",
      "patch_size = 16",
      "patches = image.unfold(2, patch_size, patch_size).unfold(3, patch_size, patch_size)",
      "patches = patches.permute(0, 2, 3, 1, 4, 5)",
      "patches = patches.reshape(1, -1, 3 * patch_size * patch_size)",
      "print(patches.shape)"
    ),
    observe: "The image becomes 196 patch vectors before projection. Smaller patches increase token count and attention cost.",
    tryIt: "Change patch size to 8 and calculate the new number of visual positions before running.",
  },
  "interpretability-editing": {
    title: "Turn an activation hypothesis into an intervention",
    language: "Python-like pseudocode",
    setup: "Patching tests whether a selected activation can causally transfer behavior between matched runs.",
    predict: "Why are a clean run, corrupted run, and sham patch all needed?",
    code: lines(
      "clean_cache = model.run_with_cache(clean_prompt)",
      "corrupt_output, corrupt_cache = model.run_with_cache(corrupted_prompt)",
      "",
      "def patch(activation, hook):",
      "    return clean_cache[hook.name]",
      "",
      "patched_output = model.run_with_hook(corrupted_prompt, layer, patch)",
      "effect = score(patched_output) - score(corrupt_output)",
      "compare_with_sham_and_neighbor_patches(effect)"
    ),
    observe: "A controlled behavioral change supports a scoped causal claim; it does not prove a complete, localized human-readable mechanism.",
    tryIt: "Repeat across paraphrases, nearby layers, positions, and unrelated control behaviors.",
  },
};

export const codeExampleCount = Object.keys(lessonCodeExamples).length;
