import type { ThreeStoryConcept } from "./three-story-math";

export type LessonMotionStage = {
  label: string;
  title: string;
};

export type LessonMotionStory = {
  concept: ThreeStoryConcept;
  headline: string;
  intro: string;
  stages: [LessonMotionStage, LessonMotionStage, LessonMotionStage, LessonMotionStage];
};

function motion(
  concept: ThreeStoryConcept,
  headline: string,
  intro: string,
  labels: [string, string, string, string],
  titles: [string, string, string, string],
): LessonMotionStory {
  return {
    concept,
    headline,
    intro,
    stages: labels.map((label, index) => ({ label, title: titles[index] })) as LessonMotionStory["stages"],
  };
}

export const lessonMotionStories: Record<string, LessonMotionStory> = {
  introduction: motion(
    "pipeline",
    "Language generation is one repeated prediction, not one finished answer.",
    "The field uncoils into a left-to-right token path. Each scroll step adds the context, probability distribution, and selected continuation that make generation autoregressive.",
    ["CONTEXT", "LOGITS", "NEXT TOKEN", "REPEAT"],
    ["The prompt establishes what the next prediction may depend on.", "One forward pass scores every vocabulary token.", "A decoding rule turns scores into one new token.", "The chosen token returns as context for the next pass."],
  ),
  "tensors-shapes": motion(
    "coordinates",
    "A tensor operation is valid only when every axis has a job.",
    "The points begin on a rectangular index grid, then move into the transformed coordinates produced by matrix multiplication. Rows, columns, and output width remain visibly distinct.",
    ["AXES", "VALUES", "MULTIPLY", "OUTPUT SHAPE"],
    ["Name batch, position, and feature axes before calculating.", "A coordinate stores a number; its axis gives that number a role.", "Matrix multiplication mixes the shared inner dimension.", "The untouched axes and new output width determine the result."],
  ),
  "probability-softmax": motion(
    "distribution",
    "Softmax turns relative scores into a budget of probability mass.",
    "Columns reorganize into a distribution: large logits receive taller stacks, normalization fixes the total mass at one, and the target column determines cross-entropy loss.",
    ["LOGITS", "EXPONENTIATE", "NORMALIZE", "TARGET LOSS"],
    ["Logits rank possibilities without yet being probabilities.", "Exponentiation makes score gaps matter multiplicatively.", "Division by the shared sum makes all probabilities add to one.", "Cross-entropy reads how much mass reached the correct class."],
  ),
  "gradients-backprop": motion(
    "optimization",
    "Backpropagation carries one output error to every responsible parameter.",
    "The surface shows a loss landscape while the bright trace moves backward through dependencies and downhill through parameter space.",
    ["FORWARD VALUE", "LOSS", "LOCAL DERIVATIVES", "PARAMETER GRADIENT"],
    ["The forward pass records the quantities that produced the prediction.", "A scalar loss states how wrong this example was.", "The chain rule multiplies local sensitivities along each path.", "Each parameter receives a direction that would change the loss."],
  ),
  optimizers: motion(
    "optimization",
    "An optimizer converts a noisy gradient into a controlled parameter step.",
    "The point trace descends a curved valley. Oscillation, accumulated direction, and step size are visible as different paths rather than interchangeable update rules.",
    ["GRADIENT", "OPTIMIZER STATE", "STEP SIZE", "NEW WEIGHTS"],
    ["The gradient supplies a local direction, not a complete route.", "Momentum or moment estimates remember useful recent structure.", "The learning rate scales how far the update travels.", "The new parameters change every later forward pass."],
  ),
  tokenization: motion(
    "segmentation",
    "Tokenization cuts visible text into the discrete symbols a model can process.",
    "A continuous character line separates into uneven groups. The gaps emphasize that token boundaries come from a vocabulary and algorithm, not from human word boundaries.",
    ["TEXT", "BOUNDARIES", "TOKEN IDS", "SEQUENCE"],
    ["Start with characters exactly as encoded, including spaces and bytes.", "The tokenizer selects vocabulary pieces using fixed rules.", "Each selected piece receives a discrete integer label.", "The resulting ID sequence sets context length and prediction steps."],
  ),
  "embedding-layer": motion(
    "embedding",
    "A token ID becomes one learned point in a continuous vector space.",
    "The scene begins as rows in an embedding table. Scrolling selects rows, releases their coordinates, and clusters vectors that training has made useful in similar contexts.",
    ["TOKEN ID", "ROW LOOKUP", "DENSE VECTOR", "LEARNED GEOMETRY"],
    ["An integer ID names a row; its numeric size carries no meaning.", "Lookup copies the selected learned row into the sequence state.", "The row supplies one coordinate for every model feature.", "Distances and directions reflect learned usage, not dictionary definitions."],
  ),
  "positional-encoding": motion(
    "position",
    "Position changes identical token content into order-aware states.",
    "Tokens start on a flat line and wind into a position-dependent helix. Equal content can therefore occupy different states without changing its token identity.",
    ["TOKEN CONTENT", "POSITION INDEX", "POSITION SIGNAL", "ORDER-AWARE STATE"],
    ["Token embeddings alone do not say which occurrence came first.", "Each sequence slot supplies a distinct index or relative offset.", "Addition or rotation injects that position into the representation.", "Attention can now distinguish reordered sequences and relative distance."],
  ),
  attention: motion(
    "attention",
    "Attention builds each token state from a weighted view of visible tokens.",
    "Four head lanes begin with equal token grids. As the query advances, relevant keys pull their values toward the output while weak matches stay distant.",
    ["QUERY", "KEY SCORES", "MASK + SOFTMAX", "VALUE MIX"],
    ["The current token projects a query describing what it needs.", "Dot products compare that query with every allowed key.", "Masking removes illegal positions before weights are normalized.", "The weighted value sum writes context into the current token state."],
  ),
  "layers-of-understanding": motion(
    "layers",
    "Transformer layers repeatedly revise the same residual stream.",
    "Six stacked rings represent successive blocks. Their changing phase shows attention and MLP updates accumulating while a residual path preserves earlier information.",
    ["RESIDUAL STATE", "ATTENTION UPDATE", "MLP UPDATE", "DEEPER STATE"],
    ["Each block receives the complete current token representation.", "Attention moves information between token positions.", "The MLP transforms features independently at each position.", "Residual additions let later layers reuse and refine earlier features."],
  ),
  "learning-to-predict": motion(
    "distribution",
    "Next-token training compares every context position with the token that actually followed.",
    "Probability columns sharpen around shifted targets. The animation connects causal context, vocabulary logits, target alignment, and the averaged training signal.",
    ["CAUSAL CONTEXT", "VOCAB LOGITS", "SHIFTED TARGET", "MEAN LOSS"],
    ["A position may use only tokens at or before that position.", "The language-model head scores the full vocabulary at each slot.", "Targets are the input sequence shifted one token to the left.", "Valid token losses are averaged into the scalar used for learning."],
  ),
  "gpt2-from-scratch": motion(
    "layers",
    "A causal decoder is a shape-preserving stack around one prediction contract.",
    "The layered field follows token IDs through embeddings, repeated decoder blocks, and a vocabulary projection. Scroll progress assembles the complete executable path.",
    ["TOKEN IDS", "EMBED + POSITION", "DECODER BLOCKS", "VOCAB LOGITS"],
    ["The batch enters as integer token IDs with a causal target shift.", "Token and position information form the initial residual stream.", "Masked attention and MLP sublayers repeatedly update that stream.", "Normalization and the output head produce next-token scores."],
  ),
  "pretraining-overview": motion(
    "training",
    "Pretraining repeats prediction and updating across a governed stream of text.",
    "Batches move across a changing loss surface toward checkpoint states. The scene ties data, objective, optimization, and evaluation into one loop.",
    ["DATA BATCH", "PREDICTION LOSS", "DISTRIBUTED UPDATE", "CHECKPOINT"],
    ["A sampled token batch defines the evidence available for this step.", "Causal prediction turns that batch into many supervised targets.", "Workers aggregate gradients before the optimizer changes shared weights.", "A checkpoint preserves weights, state, configuration, and evidence for review."],
  ),
  "objectives-details": motion(
    "training",
    "The objective decides exactly which positions teach which predictions.",
    "The grid separates input positions, legal context, selected targets, and loss terms. Changing the objective visibly changes the gradient-producing cells.",
    ["INPUT TOKENS", "VISIBILITY RULE", "TARGETS", "LOSS MASK"],
    ["The training example first becomes a fixed tensor of token IDs.", "Architecture and mask rules define what each position may inspect.", "The objective assigns a desired output to selected positions.", "Only valid, intended positions contribute to the optimizer signal."],
  ),
  "scaling-laws": motion(
    "optimization",
    "Scaling is a budget allocation problem across model, data, and compute.",
    "Candidate runs descend different cost-quality paths. The converging traces show why a fitted trend guides experiments but does not remove recipe and data confounds.",
    ["PARAMETERS", "TRAINING TOKENS", "COMPUTE BUDGET", "MEASURED FRONTIER"],
    ["Model size controls capacity and the cost of each token.", "Training tokens determine how much evidence updates those parameters.", "Hardware time constrains which size–data combinations are feasible.", "Held-out measurements reveal the useful frontier for this exact setup."],
  ),
  "data-engineering": motion(
    "data",
    "Training data becomes a curriculum only after filtering, deduplication, and mixing.",
    "Separate source clusters feed a central stream; rejected outliers leave the field while retained documents are weighted into batches.",
    ["SOURCES", "FILTER + GOVERN", "DEDUPLICATE", "MIX + SAMPLE"],
    ["Every source arrives with different quality, rights, language, and risk.", "Policy and quality checks remove material that should not train the model.", "Deduplication limits repeated documents and contaminated splits.", "Mixture weights decide which retained examples the optimizer sees most often."],
  ),
  infrastructure: motion(
    "systems",
    "Distributed training keeps many devices synchronized on one logical update.",
    "Device rings exchange shards and gradients around a shared center. The animation exposes communication and recovery as part of correctness, not background plumbing.",
    ["GLOBAL BATCH", "SHARD WORK", "COLLECTIVES", "CONSISTENT UPDATE"],
    ["The global batch is partitioned across devices and parallel dimensions.", "Each worker computes its local forward and backward contributions.", "Collective communication combines the values the algorithm requires.", "All replicas must apply the same valid update or recover from a known checkpoint."],
  ),
  "advanced-objectives": motion(
    "training",
    "Alternative pretraining objectives change the evidence a representation must preserve.",
    "Different target masks reshape the training field. Dense, corrupted, and multi-token targets pull representations toward different useful structures.",
    ["INPUT CORRUPTION", "TARGET DESIGN", "TRAINING SIGNAL", "TRANSFER TEST"],
    ["The objective may hide, replace, reorder, or group parts of an example.", "Targets specify what information must be reconstructed or predicted.", "That target pattern changes where gradients enter the network.", "Only downstream evaluation shows whether the learned representation transfers."],
  ),
  "pretraining-evaluation": motion(
    "evaluation",
    "A checkpoint is useful only when multiple measurements agree on what changed.",
    "Samples spread across metric lanes rather than collapsing into one score. Progress reveals trends, slices, and regressions that an average can hide.",
    ["CHECKPOINT", "HELD-OUT LOSS", "CAPABILITY SLICES", "REGRESSION DECISION"],
    ["Freeze a checkpoint and its exact tokenizer, config, and data revision.", "Held-out loss tests prediction on examples excluded from optimization.", "Task and subgroup slices probe abilities that one average cannot represent.", "Selection weighs gains, regressions, uncertainty, and contamination evidence."],
  ),
  "olmo3-case-study": motion(
    "pipeline",
    "OLMo 3 separates broad pretraining, targeted mid-training, and long-context adaptation.",
    "The helix straightens into the published model-flow stages so each data change and checkpoint can be inspected without treating the release as one monolithic run.",
    ["DOLMA 3 MIX", "DOLMINO", "LONGMINO", "OLMES EVIDENCE"],
    ["Broad pretraining establishes the base checkpoint and general token distribution.", "Dolmino targets selected capability mixtures from that known base.", "Longmino changes the context-length curriculum in a later stage.", "Released evaluations and artifacts bound which conclusions the flow supports."],
  ),
  "instruction-tuning-rlhf": motion(
    "preference",
    "Post-training changes how a base model responds without replacing its pretraining history.",
    "Three response branches narrow toward desired assistant behavior. Demonstrations, comparisons, and outcome signals remain distinct routes into the policy.",
    ["BASE MODEL", "DEMONSTRATIONS", "PREFERENCES", "OUTCOME FEEDBACK"],
    ["The base model begins as a next-token predictor over its pretraining mixture.", "Supervised examples teach the prompt-to-response format directly.", "Pairwise preferences teach relative desirability between plausible responses.", "Outcome feedback updates behavior using rewards that may arrive after a trajectory."],
  ),
  "posttraining-overview": motion(
    "preference",
    "Post-training turns desired behavior into several different learning signals.",
    "Candidate responses begin far apart, then demonstrations, preference margins, and policy constraints pull the distribution toward an assistant contract.",
    ["PROMPT", "CANDIDATE RESPONSES", "BEHAVIOR SIGNAL", "UPDATED POLICY"],
    ["A prompt defines the context in which behavior will be judged.", "The current policy supplies plausible outputs rather than one fixed label.", "Demonstration, comparison, or reward data expresses a different kind of supervision.", "The update changes response probabilities and must be checked for regressions."],
  ),
  sft: motion(
    "training",
    "Supervised fine-tuning learns an assistant response from explicit demonstrations.",
    "Prompt and response tokens occupy one sequence, while the loss field lights only intended answer positions. This makes masking and template boundaries visible.",
    ["CHAT TEMPLATE", "PROMPT MASK", "RESPONSE TARGETS", "SFT UPDATE"],
    ["The template serializes roles, separators, and turns into exact tokens.", "Prompt tokens usually provide context without becoming answer targets.", "Response tokens are shifted to create supervised next-token labels.", "The optimizer increases the likelihood of demonstrated behavior within that format."],
  ),
  "preference-optimization": motion(
    "preference",
    "Preference optimization increases the margin between chosen and rejected responses.",
    "Paired branches share a prompt, then move together or apart according to relative log-probability and reference-policy terms.",
    ["SHARED PROMPT", "CHOSEN / REJECTED", "LOG-RATIO MARGIN", "POLICY UPDATE"],
    ["Both responses must be evaluated under the same prompt and serialization.", "A preference label identifies a relative choice, not an absolute truth score.", "The objective compares response likelihoods, often relative to a reference policy.", "The gradient raises the preferred margin while regularization limits drift."],
  ),
  "rl-fundamentals": motion(
    "optimization",
    "Reinforcement learning assigns credit from outcomes back to sampled actions.",
    "A trajectory crosses a reward surface, then the return and baseline reshape its update. The path makes delayed credit visibly different from token labels.",
    ["STATE", "SAMPLED ACTION", "RETURN", "ADVANTAGE UPDATE"],
    ["The state summarizes information available before an action is chosen.", "The policy samples an action from a probability distribution.", "Later rewards are accumulated into a return for the trajectory.", "Advantage compares that return with a baseline to scale the policy gradient."],
  ),
  rlhf: motion(
    "preference",
    "RLHF trains a reward proxy, then optimizes the policy under a drift constraint.",
    "Human-ranked response branches first train a scoring surface; policy trajectories then move uphill while a reference tether limits overoptimization.",
    ["HUMAN RANKINGS", "REWARD MODEL", "POLICY ROLLOUTS", "PPO + KL"],
    ["Annotators compare sampled responses under a defined rubric.", "A reward model learns to predict those finite, noisy preferences.", "The current policy generates fresh trajectories near its own distribution.", "PPO-style constraints and KL regularization limit each reward-seeking update."],
  ),
  "tools-safety": motion(
    "security",
    "Tool safety is enforced at the action boundary, not by polite model intent.",
    "Requests approach a permission boundary. Authorized, schema-valid actions enter the protected center; injected or excessive actions remain outside with an auditable trace.",
    ["MODEL REQUEST", "SCHEMA CHECK", "AUTHORIZATION", "RESULT + TRACE"],
    ["The model proposes a typed action; it does not directly possess authority.", "Validation rejects malformed names, arguments, and unexpected output shapes.", "Independent policy checks identity, scope, confirmation, and least privilege.", "Execution returns bounded results while logs preserve what was attempted."],
  ),
  "tulu3-case-study": motion(
    "pipeline",
    "Tülu 3 and DR Tulu expose a staged route from instruction data to research-agent behavior.",
    "The release flow separates supervised instruction following, preference learning, reinforcement signals, and agent evaluation so evidence stays attached to the stage that produced it.",
    ["SFT MIX", "PREFERENCE STAGE", "RL SIGNAL", "AGENT EVALUATION"],
    ["Instruction mixtures establish response format and baseline task behavior.", "Preference data reshapes relative response likelihoods.", "RL stages optimize verifier or outcome signals under a stated recipe.", "Agent and safety evaluations test whether the combined policy transfers beyond training prompts."],
  ),
  "decoding-sampling": motion(
    "decoding",
    "Decoding turns one probability distribution into one irreversible token choice.",
    "Many candidate branches fan out from each step. Temperature reshapes them, truncation removes branches, and sampling extends only the selected path.",
    ["LOGITS", "TEMPERATURE", "TOP-K / TOP-P", "SAMPLED TOKEN"],
    ["The model emits unnormalized scores for every vocabulary item.", "Temperature changes distribution sharpness before probabilities are formed.", "Top-k or top-p removes candidates and renormalizes the survivors.", "One chosen token joins the context and changes the next distribution."],
  ),
  "generation-kv-cache": motion(
    "memory",
    "The KV cache trades growing memory for avoided attention recomputation.",
    "A prompt grid coils into persistent key/value memory. Each decode step adds one cache position while issuing only a new query.",
    ["PREFILL", "LAYER K/V", "NEW QUERY", "APPEND + DECODE"],
    ["Prefill processes prompt positions in parallel and creates every layer state.", "Keys and values for earlier positions persist in cache memory.", "Decode computes one query for the newly generated token at each layer.", "The new K/V entry is appended before the next sequential token step."],
  ),
  "quantization-memory": motion(
    "compression",
    "Quantization snaps continuous weights onto a smaller set of representable levels.",
    "A dense floating-point field collapses onto a coarser lattice. Outliers and group boundaries remain visible as the places where rounding error concentrates.",
    ["FLOAT VALUES", "SCALE + ZERO POINT", "ROUND + CLIP", "LOW-BIT KERNEL"],
    ["Floating values begin with a range that may vary sharply by channel.", "Scale and optional zero-point map that range to integer levels.", "Rounding and clipping introduce an error that must be measured.", "Compatible kernels determine whether compact storage becomes real speed."],
  ),
  "serving-systems": motion(
    "systems",
    "A serving scheduler continuously repacks finite compute around changing requests.",
    "Request groups circulate through prefill and decode slots. Finished sequences leave the ring so new work can enter without padding every request to the longest one.",
    ["ARRIVAL QUEUE", "PREFILL", "CONTINUOUS DECODE", "RETIRE / ADMIT"],
    ["Admission control decides which requests may consume memory and compute.", "Prefill work creates the first token and each request's cache state.", "Continuous batching groups active decode steps while sequences differ in length.", "Completed requests release slots that the scheduler immediately reuses."],
  ),
  "test-time-compute": motion(
    "routing",
    "Test-time compute helps only when extra candidates and verification earn their cost.",
    "A query routes to one or several reasoning branches. Only candidates that survive a separate checker converge on the final answer path.",
    ["PROBLEM", "COMPUTE BUDGET", "CANDIDATES", "VERIFIER"],
    ["Task value and uncertainty determine whether escalation is justified.", "The policy allocates sequential steps, parallel samples, or tool checks.", "Useful extra compute must create meaningfully different candidate solutions.", "A trustworthy verifier selects, rejects, or requests another bounded attempt."],
  ),
  "context-engineering": motion(
    "data",
    "A good context is an ordered working set, not a maximum-length transcript.",
    "Instruction, evidence, examples, and state begin as separate source clusters. Only relevant, authorized pieces converge into the model's current prompt.",
    ["POLICY", "EVIDENCE", "EXAMPLES + STATE", "ORDERED CONTEXT"],
    ["System and developer policy establish the highest-authority task contract.", "Retrieved or user-provided evidence must stay distinguishable from instructions.", "Examples and state should earn their limited context space through relevance.", "Delimiters and ordering create the exact conditional input the model receives."],
  ),
  rag: motion(
    "retrieval",
    "RAG succeeds only when needed evidence survives every retrieval stage.",
    "Document clusters surround a query. Relevant chunks move inward through retrieval and reranking; irrelevant material stays outside the generation context.",
    ["DOCUMENT CHUNKS", "QUERY EMBEDDING", "RETRIEVE + RERANK", "GROUNDED ANSWER"],
    ["Ingestion creates searchable chunks while preserving source and access metadata.", "The query becomes dense, sparse, or hybrid retrieval features.", "Candidate recall comes first; reranking then spends effort on precision.", "Generation must cite evidence that actually entails each supported claim."],
  ),
  "agent-loops": motion(
    "agent",
    "An agent alternates between model decisions and externally checked state changes.",
    "The orbit closes only after observation returns from a tool. Stop conditions and permissions interrupt the loop before it can become unbounded.",
    ["GOAL + STATE", "DECIDE", "TOOL ACTION", "OBSERVE / STOP"],
    ["The loop begins with a goal, current state, budget, and policy constraints.", "The model proposes a next action from the information it currently has.", "A tool layer validates and executes the action under real authorization.", "The result updates state; a stop rule ends or bounds the next cycle."],
  ),
  "evaluation-design": motion(
    "evaluation",
    "An evaluation is a measurement system whose cases, rubric, and judge can all fail.",
    "Case rows spread across multiple metric lanes. Residuals reveal disagreements and slice failures that one aggregate score would conceal.",
    ["TASK CONTRACT", "TEST CASES", "SCORER / RUBRIC", "ERROR ANALYSIS"],
    ["Define the behavior and decision the evaluation is meant to measure.", "Cases must represent important distributions, boundaries, and adversarial failures.", "Deterministic checks, humans, and model judges each need calibrated roles.", "Inspect disagreements and slices before turning scores into a product decision."],
  ),
  "security-privacy": motion(
    "security",
    "Untrusted content must never inherit the authority of the system that reads it.",
    "Trusted state occupies a protected center while injected instructions and sensitive data press against the boundary. Policy moves unsafe actions farther away.",
    ["TRUST BOUNDARIES", "UNTRUSTED INPUT", "POLICY ENFORCEMENT", "SAFE EFFECT"],
    ["Label which components may instruct, supply data, authorize, or execute.", "Retrieved pages and user text remain untrusted even when they look imperative.", "Deterministic controls validate permissions, data flow, and allowed tool effects.", "The system minimizes disclosure and limits the blast radius of a bad decision."],
  ),
  "observability-governance": motion(
    "evaluation",
    "Production governance connects each model output to a trace, metric, and decision owner.",
    "Requests cross metric lanes for quality, latency, cost, and risk. Diverging points become diagnosable alerts instead of disappearing inside an average.",
    ["REQUEST TRACE", "STAGE METRICS", "ALERT + SLICE", "OWNER DECISION"],
    ["A trace records model, prompt, retrieval, tools, timing, and outcome identifiers.", "Stage-level metrics separate retrieval, generation, safety, latency, and cost failures.", "Alerts use slices and thresholds tied to real service objectives.", "Named owners can investigate, degrade, roll back, or update policy with evidence."],
  ),
  distillation: motion(
    "compression",
    "Distillation trains a smaller model to reproduce useful teacher behavior.",
    "A wide teacher distribution contracts into a smaller student lattice. The animation preserves soft relative probabilities rather than only the top label.",
    ["TEACHER LOGITS", "SOFT TARGETS", "STUDENT LOSS", "COMPACT MODEL"],
    ["The teacher exposes relative scores or generated examples for chosen inputs.", "Temperature can reveal relationships hidden by a hard argmax label.", "The student balances distillation targets with task or ground-truth supervision.", "Evaluation checks which capabilities survived the reduced capacity and cost."],
  ),
  lora: motion(
    "adapter",
    "LoRA learns a low-rank side path while the original weight matrix stays frozen.",
    "Most points remain in fixed base columns. A small side stream passes through two narrow factors and returns as an additive weight update.",
    ["FROZEN WEIGHT", "LOW-RANK A", "LOW-RANK B", "ADDITIVE DELTA"],
    ["The pretrained matrix continues to provide the base linear transformation.", "The first factor projects activations into a small rank dimension.", "The second factor expands that small representation back to output width.", "Their product is scaled and added without storing a full trainable matrix."],
  ),
  moe: motion(
    "routing",
    "A sparse MoE activates selected experts for each token instead of every expert.",
    "Six expert clusters surround the router. Only the highest-scoring routes move inward; the rest remain inactive for that token.",
    ["TOKEN STATE", "ROUTER SCORES", "TOP-K EXPERTS", "WEIGHTED COMBINE"],
    ["The token's current representation enters a learned routing function.", "The router assigns a score to each available expert.", "A sparse rule dispatches the token to only the selected experts.", "Expert outputs are weighted and returned to the residual stream."],
  ),
  "multimodal-models": motion(
    "multimodal",
    "Multimodal models must align different input structures before language decoding.",
    "Image-patch and text-token streams begin apart, then project toward a shared interface where cross-modal attention can combine them.",
    ["MODALITY ENCODERS", "PATCH / TOKEN FEATURES", "SHARED PROJECTION", "CROSS-MODAL DECODE"],
    ["Each modality first needs an encoder suited to its raw structure.", "Images become patches or features while text becomes token states.", "Projection layers match the dimensions and training interface used for fusion.", "Attention and decoding condition language outputs on the aligned evidence."],
  ),
  "interpretability-editing": motion(
    "interpretability",
    "Interpretability turns distributed activations into testable causal hypotheses.",
    "A dense activation torus opens into a sparse feature line. Probes identify correlations; interventions move only the features whose causal effect is being tested.",
    ["ACTIVATIONS", "FEATURE HYPOTHESIS", "INTERVENTION", "CAUSAL EVIDENCE"],
    ["Record internal states for a precisely defined set of inputs and positions.", "A probe or decomposition proposes a human-interpretable feature.", "Ablation, patching, or editing changes that feature under controlled conditions.", "Behavioral differences support a bounded causal claim only when confounds are ruled out."],
  ),
};
