export type LessonEvidence = {
  contrast: {
    title: string;
    left: { label: string; situation: string; outcome: string };
    right: { label: string; situation: string; outcome: string };
    principle: string;
  };
  transfer: { prompt: string; criteria: string[]; solution: string };
};

const evidence = (
  title: string,
  left: [string, string, string],
  right: [string, string, string],
  principle: string,
  prompt: string,
  criteria: string[],
  solution: string,
): LessonEvidence => ({ contrast: { title, left: { label: left[0], situation: left[1], outcome: left[2] }, right: { label: right[0], situation: right[1], outcome: right[2] }, principle }, transfer: { prompt, criteria, solution } });

export const lessonEvidence: Record<string, LessonEvidence> = {
  introduction: evidence(
    "The same model loop, two very different system claims",
    ["Prediction task", "Continue ‘Water freezes at …’ from learned token patterns.", "The model can assign high probability to ‘0°C’; this is a prediction, not an external verification."],
    ["Tool task", "Refund a duplicate charge for an authenticated customer.", "The model may propose a tool call, but identity, permission, execution, and receipt belong to the surrounding system."],
    "A model produces conditional token distributions. Truth checking and consequential action require evidence and controls outside that distribution.",
    "A fluent assistant answers a current weather question and then books a flight. Draw the boundary between next-token prediction, retrieved evidence, decoding, and authorized action.",
    ["Names the model's prediction role", "Places changing facts in retrieval or a tool", "Places booking authority and confirmation in runtime controls"],
    "The model predicts the answer and proposed call; a weather source supplies current evidence; decoding selects tokens; the runtime validates identity, scope, price, confirmation, and the booking receipt. Fluency alone owns none of those guarantees.",
  ),
  "tensors-shapes": evidence(
    "A valid projection and a silent broadcasting bug",
    ["Named contraction", "$X[2,3,4] @ W[4,6]$ contracts the feature axis.", "The output is $[2,3,6]$; batch and time survive."],
    ["Compatible but wrong", "A mask shaped $[T,1]$ broadcasts across an attention score tensor where $[1,1,T,T]$ was intended.", "The program runs, but masks query rows rather than forbidden key positions."],
    "Shape compatibility is necessary, not sufficient: every axis needs a semantic name and an invariant test.",
    "A grouped-query attention block has queries $[B,h_q,T,d_h]$ and keys $[B,h_{kv},T,d_h]$ with $h_q=4h_{kv}$. Describe the reshape/repetition needed before query-key multiplication and the final score shape.",
    ["Preserves batch, token, and head dimensions", "Explains how KV heads serve groups of query heads", "Produces scores $[B,h_q,T,T]$ without contracting a token axis"],
    "Group each set of four query heads with one KV head, or repeat/broadcast KV heads along the head axis deliberately. Then multiply Q by transposed K on $d_h$, yielding $[B,h_q,T,T]$.",
  ),
  "probability-softmax": evidence(
    "Stable probabilities are not the same as calibrated probabilities",
    ["Stable computation", "Logits $[1000,999,998]$ are shifted by their maximum before exponentiation.", "Softmax matches the probabilities from $[2,1,0]$ without overflow."],
    ["Calibration failure", "A classifier assigns 0.9 confidence to 100 predictions but only 70 are correct.", "Its softmax is numerically valid yet overconfident; calibration must be measured against outcomes."],
    "Numerical stability preserves the intended distribution; calibration asks whether confidence frequencies match reality.",
    "Two token positions have target probabilities 0.8 and 0.2, but the second is padding. Compute the unmasked mean loss and the correctly masked mean, then explain which should train the model.",
    ["Uses $-\\log p$ for both raw losses", "Excludes the padding position from numerator and denominator", "Explains why a valid probability can still be an invalid training target"],
    "The raw losses are about 0.223 and 1.609, so the unmasked mean is 0.916. With the padding position masked, the training mean is 0.223; the 0.2 probability should not create a gradient for a token that is not a target.",
  ),
  "gradients-backprop": evidence(
    "A correct local derivative and a failed optimization step",
    ["Gradient check", "Autograd reports $dL/dw=0.600$ and a centered finite difference with $\\epsilon=10^{-4}$ reports 0.600.", "Agreement supports the derivative implementation at this point."],
    ["Oversized step", "The same derivative is multiplied by a learning rate 100 times larger.", "Loss rises; this does not invalidate backprop because a derivative is local and the optimizer chose the step."],
    "Differentiate the computation first; judge the update rule and step size separately.",
    "For $X[2,2]$, $W[2,3]$, $Y=XW$, and $L=\\sum Y^2$, trace the shapes of $dL/dY$, $dL/dW$, and $dL/dX$ and name the matrix products.",
    ["Keeps $dL/dY$ at $[2,3]$", "Uses $X^T(dL/dY)$ for $dL/dW[2,3]$", "Uses $(dL/dY)W^T$ for $dL/dX[2,2]$"],
    "$dL/dY=2Y$ has the output shape. The weight gradient accumulates examples with $X^T(dL/dY)$, while the input gradient sends sensitivity backward with $(dL/dY)W^T$.",
  ),
  optimizers: evidence(
    "SGD and Adam see the same gradient but keep different state",
    ["Noisy valley", "Gradients alternate sharply across one axis and remain small along another.", "Momentum SGD smooths noise but uses one global scale, so progress along the flat axis can be slow."],
    ["Adaptive state", "Adam tracks first and second moments for each parameter.", "It rescales coordinates and often moves faster initially, at the cost of roughly two state tensors and different generalization behavior."],
    "Optimizer choice changes how gradients become updates; it does not change how backprop computed those gradients.",
    "A 7B-parameter model is memory-bound during training. Compare SGD with momentum and AdamW in fp32 optimizer state, then recommend one under a fixed memory budget and state the quality evidence still needed.",
    ["Counts optimizer-state tensors rather than only parameters", "Separates memory feasibility from convergence quality", "Proposes a controlled run instead of claiming one optimizer universally wins"],
    "Momentum needs one main state tensor per parameter; AdamW commonly needs two. If AdamW does not fit, sharding, lower-precision state, an alternative optimizer, or momentum may be required. The final choice needs matched-token learning curves and held-out quality, not memory arithmetic alone.",
  ),
  tokenization: evidence(
    "Token boundaries change cost and meaning across inputs",
    ["Natural language", "A frequent English phrase is represented by a few learned subwords.", "Shorter token sequences reduce context and compute, but the boundaries remain model-specific."],
    ["Code and bytes", "Indentation, an unseen identifier, emoji, and invalid UTF-8-like bytes enter the same tokenizer.", "Whitespace and byte fallbacks can dominate token count; decode behavior and round-trip assumptions must be tested."],
    "A tokenizer is part of the model contract, not a neutral preprocessing utility.",
    "You must choose between two model/tokenizer pairs for English support, Japanese support, and code. Design a four-string encode/decode and cost test, including one byte-heavy edge case, and state the decision rule.",
    ["Tests multilingual text, code/whitespace, and a byte-heavy case", "Checks exact round-trip behavior as well as token count", "Treats tokenizer and model as an inseparable deployed pair"],
    "Run the exact pinned tokenizers, record IDs, decoded text, token counts, and any normalization. Prefer the pair that meets task quality and context/cost constraints; never transplant tokenizer IDs into unrelated model weights.",
  ),
  "embedding-layer": evidence(
    "Static lookup identity versus contextual separation",
    ["Before blocks", "The token ID for ‘bank’ retrieves the same embedding-table row in both sentences.", "Only position information may differ before contextual mixing."],
    ["After blocks", "Attention and MLP updates incorporate ‘river’ or ‘loan’ context.", "The hidden states can separate even though their lookup origin was identical."],
    "Embedding rows are learned input parameters; contextual hidden states are computed representations.",
    "A nearest-neighbor demo shows ‘bank’ close to ‘loan’. Explain why that result cannot prove the model will interpret river-bank prompts incorrectly, and name the hidden states you would compare instead.",
    ["Distinguishes embedding-table neighbors from contextual states", "Notes that a 2-D projection can distort neighborhoods", "Compares the same token position at named layers across controlled contexts"],
    "The lookup is context-free and the plotted projection is lossy. Extract the token's full hidden state after specified Transformer layers in matched finance and river sentences, then compare distances and downstream behavior.",
  ),
  "positional-encoding": evidence(
    "Absolute labels and relative rotations fail differently",
    ["Learned absolute", "Each position adds a learned vector available only for trained indices.", "Order is explicit, but extrapolating beyond trained positions introduces untrained rows or requires interpolation."],
    ["RoPE", "Query/key coordinate pairs rotate by position-dependent phases.", "Dot products encode relative offsets, yet long-context extension can still fail when frequencies and training distribution are mismatched."],
    "Encoding a position is not the same as learning to use arbitrarily long context.",
    "A model trained to length 2K is deployed at 16K after RoPE scaling. Specify one positional diagnostic and one task diagnostic that would falsify ‘the context extension works.’",
    ["Checks phase/attention behavior rather than only accepting the configured length", "Uses a retrieval or order-sensitive task across distances", "Separates ability to load 16K tokens from effective use of them"],
    "Inspect attention/logit stability by relative distance and run controlled long-range retrieval/order tasks with distractors. Passing allocation and avoiding a crash only establish capacity, not usable long-context behavior.",
  ),
  attention: evidence(
    "Information routing changes when the mask changes",
    ["Causal decoder", "Position 3 may attend only to keys 0–3.", "Future scores are masked before softmax, so earlier outputs cannot depend on later tokens."],
    ["Bidirectional encoder", "Every visible position may attend to every other visible position.", "This supports full-context representations but does not define an autoregressive generation interface."],
    "Queries, keys, values, and masks specify routing; an attention heatmap alone is not a complete explanation.",
    "In ‘The glass fell because it was fragile,’ design the allowed-key set for the query ‘it’ in a causal decoder and in a bidirectional encoder, then explain what causal evidence the resulting weights do not provide.",
    ["Applies the correct future-token restriction", "Explains why bidirectional access differs", "Does not equate high attention weight with causal responsibility"],
    "The causal query can use only positions through ‘it’; the encoder can also use ‘was fragile.’ Either pattern shows routing under that head, not proof that the attended token caused the final prediction—intervention would be needed.",
  ),
  "layers-of-understanding": evidence(
    "Residual shape preservation versus normalization failure",
    ["Pre-norm block", "$x[ B,T,d]$ is normalized, transformed, and added back to the same-width stream twice.", "Attention and MLP updates can be removed or scaled while the residual path preserves a direct route."],
    ["Broken branch", "An MLP returns $[B,T,2d]$ directly to a residual stream of width $d$.", "Addition fails; the second MLP projection must restore width $d$ before the residual merge."],
    "The residual stream is a shape contract and an information path, not a named collection of human concepts.",
    "A new block variant normalizes after each residual addition instead of before each sublayer. Trace one block and state which equations, initialization concerns, and checkpoint conversions change.",
    ["Writes the post-norm operation order", "Keeps every residual addition at width $d$", "Avoids claiming pre-norm and post-norm checkpoints are interchangeable"],
    "Post-norm uses $h=\\operatorname{Norm}(x+\\operatorname{Attn}(x))$ followed by another normalized residual result. Shape stays fixed, but optimization dynamics and parameter placement differ, so weights cannot be relabeled blindly.",
  ),
  "learning-to-predict": evidence(
    "Correct shifting versus silent padding loss",
    ["Valid labels", "Input [A,B,C] is paired with labels [B,C,EOS].", "Every loss position predicts the next token and contributes only where the mask permits."],
    ["Off-by-one batch", "Inputs and labels are identical, and padding IDs are scored as targets.", "The model is rewarded for copying current tokens and learning padding frequency instead of next-token prediction."],
    "Inspect decoded input-label pairs and loss masks before trusting a falling loss.",
    "Two conversations are packed into one sequence. Construct labels so assistant tokens train, user/system tokens do not, and the boundary between conversations cannot become a learned continuation.",
    ["Masks non-assistant tokens with the ignore index", "Uses an explicit end/boundary token between conversations", "Verifies one decoded packed example and contributing positions"],
    "Serialize each chat with its template and terminal token, concatenate only under an explicit packing policy, and set labels to ignore system/user/boundary positions. Decode and print the mask before training.",
  ),
  "gpt2-from-scratch": evidence(
    "A fluent sample and a correct model are different achievements",
    ["Correctness dossier", "Shift, causal-mask, overfit-one-batch, and resume tests pass.", "The model's mechanics are supported even if samples remain weak at tiny scale."],
    ["Cherry-picked fluency", "One attractive sample appears while validation loss, leakage, and mask behavior are untested.", "The sample cannot establish generalization or even causal correctness."],
    "Use invariant tests and held-out measurements before qualitative generation as evidence.",
    "Move the tiny GPT from prose to source code. Choose one architecture or tokenizer ablation, define the fixed budget and held-out split, and predict which evidence would overturn your hypothesis.",
    ["Changes exactly one treatment", "Keeps token budget/evaluation comparable", "Names a falsifying loss, syntax, or behavior outcome"],
    "A defensible example compares character versus tiny-BPE tokenization at fixed training tokens, logs held-out loss and syntax-valid completion rate, and abandons the expected winner if the paired evidence reverses.",
  ),
  "pretraining-overview": evidence(
    "Nominal token arithmetic versus actual trained tokens",
    ["Estimate", "Sequence × micro-batch × devices × accumulation predicts 131,072 tokens per optimizer step.", "This is a useful budget calculation when every slot is a real, loss-bearing token."],
    ["Measured loader", "Padding, a partial final batch, and ignored labels reduce non-padding loss tokens.", "The logged trained-token count falls below nominal capacity unless packing and drop-last rules eliminate the gap."],
    "Budget with nominal capacity; reconcile claims with counted loss-bearing tokens from the actual loader.",
    "A run finishes 3% below its stated token target although optimizer steps match the plan. List the dataloader/config fields and counters you would inspect before increasing the step count.",
    ["Checks padding, packing, drop-last, and partial batches", "Counts loss-bearing tokens rather than input slots", "Preserves recovery/data-cursor consistency when changing the plan"],
    "Inspect attention/label masks, packed utilization, sampler length, drop-last, world size, accumulation, skipped batches, and the logged non-padding-token counter. Reconcile these before changing steps, or the fix may repeat/skip data.",
  ),
  "objectives-details": evidence(
    "One text, three different loss contracts",
    ["Causal base model", "Every non-padding token predicts its successor under a causal mask.", "Prompt-like and answer-like text both contribute to the base objective."],
    ["Assistant-only SFT", "System/user tokens remain visible context but receive ignored labels; assistant tokens contribute loss.", "The same serialization now trains response behavior rather than imitation of all roles."],
    "An objective is fully specified only by visible input, targets, masks, serialization, and training stage.",
    "Given a tool-call conversation with system, user, assistant call, tool result, and final assistant answer, design two defensible label masks for different goals and explain the trade-off.",
    ["States which roles remain visible", "Marks exactly which tokens receive loss", "Connects the choice to learning tool syntax versus final-answer behavior"],
    "One policy can train both assistant call and final answer while masking system/user/tool-result text. Another can train only the final answer if calls are supplied by a fixed workflow. Compare call competence against noise and credit assignment.",
  ),
  "scaling-laws": evidence(
    "Compute-optimal training and deployment-optimal training can disagree",
    ["Training objective", "Two equal-compute runs trade model size against tokens and are compared on held-out loss.", "A fitted curve can suggest an allocation within the measured regime."],
    ["Deployment constraint", "The larger candidate meets loss targets but misses latency and memory limits.", "A smaller, more heavily trained model may deliver greater lifetime value despite a different training optimum."],
    "Scaling curves answer the objective they fit; deployment cost and quality constraints can change the optimum.",
    "Allocate a fixed compute budget between a reusable offline research model and a high-volume edge model. State the measurements, uncertainty, and decision rule for each.",
    ["Uses empirical points rather than a universal ratio", "Includes inference latency/memory for the edge model", "Reports uncertainty and refuses to extrapolate far outside measured scale"],
    "Fit or read nearby scaling points for both, but optimize the research model for capability under training compute and the edge model for lifecycle quality/cost under memory and latency constraints. Validate both with matched evaluations.",
  ),
  "data-engineering": evidence(
    "Cleaning improves one risk while sometimes harming representation",
    ["Risk removal", "Exact mirrors, leaked benchmark keys, secrets, and unresolved rights are removed or quarantined.", "Memorization, contamination, privacy, and legal risk fall."],
    ["Over-filtering", "A perplexity or language-ID filter rejects dialectal and minority-language documents at higher rates.", "Average cleanliness rises while representation and downstream coverage degrade."],
    "Every filter needs slice-level before/after measurements and a reversible, versioned decision record.",
    "A new quality classifier removes 20% of the corpus and improves validation loss, but Swahili retention falls 60%. Decide whether to ship the filter and design the next test.",
    ["Rejects an aggregate-only decision", "Audits false positives with domain/language reviewers", "Proposes threshold/sampling changes and downstream slice evaluation"],
    "Do not ship unchanged. Sample removed/kept documents by language and domain, measure label error, tune or branch thresholds, preserve licensed high-quality Swahili data, and compare both global and slice outcomes on a controlled run.",
  ),
  infrastructure: evidence(
    "Memory ownership and communication are different bottlenecks",
    ["Data parallel", "Each device owns full weights and a different micro-batch, then all-reduces gradients.", "Simple scaling increases batch throughput but replicates model and optimizer state."],
    ["Tensor parallel", "Devices own slices of large matrix operations and exchange partial activations within layers.", "Weights fit differently, but frequent collectives can make network topology decisive."],
    "Name what each device owns, when it communicates, and what must be checkpointed before choosing a parallel strategy.",
    "A model fits only with sharded optimizer state, but throughput collapses after adding tensor parallelism across slow inter-node links. Propose a revised topology and a recovery test.",
    ["Keeps high-frequency tensor-parallel collectives within fast links", "Uses sharding/data parallelism across slower links deliberately", "Tests a checkpoint with weights, optimizer, RNG, and data position"],
    "Place tensor-parallel groups within a node/NVLink island, then shard or data-parallel across nodes as memory permits. Benchmark collective time and prove resume equivalence from a deliberately interrupted run.",
  ),
  "advanced-objectives": evidence(
    "An objective family and a production mixture are different artifacts",
    ["Canonical FIM", "Prefix and suffix are reordered with sentinel tokens and the middle is predicted causally.", "The interface teaches insertion without changing the basic token cross-entropy."],
    ["Mixed recipe", "A decoder trains on a documented mixture of ordinary causal and FIM examples.", "Mixture weight, serialization variants, and sampling policy decide whether general generation is preserved."],
    "Naming FIM is not enough; a reproducible recipe pins serialization and mixture allocation.",
    "A code model improves infilling but regresses left-to-right completion after raising FIM to 90%. Design an ablation that distinguishes mixture imbalance from a tokenizer or evaluation bug.",
    ["Compares multiple FIM weights at fixed tokens", "Keeps tokenizer/serialization and evaluation versions pinned", "Measures both infilling and ordinary completion with confidence intervals"],
    "Run matched-token mixtures such as 0%, 50%, and 90% FIM using the same base configuration. Validate decoded sentinel ordering, then evaluate both task families and inspect whether the trade-off follows mixture weight.",
  ),
  "pretraining-evaluation": evidence(
    "A healthy loss curve and a contaminated capability jump",
    ["Healthy signal", "Train and held-out loss fall together while capability slices improve gradually and throughput remains stable.", "Multiple signal families support continued training."],
    ["Confounded jump", "One benchmark rises sharply after its solutions enter the data mixture while clean held-out loss barely changes.", "The score is contaminated evidence, not a broad capability gain."],
    "Intrinsic, capability, contamination, and systems metrics answer different questions and must be interpreted together.",
    "At step 80K, validation loss improves, math accuracy rises, code accuracy falls, and tokens/second drops 25%. Choose the next action and the minimum slices needed before continuing.",
    ["Avoids reducing the decision to one average", "Separates data/capability regression from systems slowdown", "Defines a stop or investigation rule before more compute"],
    "Pause escalation: verify hardware/input stalls, inspect code-data mixture and clean code slices, confirm math contamination checks, and resume only after throughput and regression causes have bounded explanations.",
  ),
  "olmo3-case-study": evidence(
    "Stage-specific evidence beats one final leaderboard score",
    ["Targeted mid-training", "Math/code deficits motivate a controlled data-stage change and stage-delta evaluation.", "The hypothesis is tied to the distribution introduced at that stage."],
    ["Wrong intervention", "A long-context stage is changed to fix short code generation without evidence that context use is the bottleneck.", "A final score may move, but the causal story and comparison budget are confounded."],
    "Choose the earliest stage whose inputs and objective plausibly match the observed deficit, then test its unique prediction.",
    "Transfer the OLMo model-flow audit to another open model release. What artifacts must exist before you accept a claim that a data stage caused a capability gain?",
    ["Requires incoming/outgoing checkpoints and exact data/config", "Requires matched evaluations and contamination controls", "Separates released evidence from author interpretation"],
    "Demand stage checkpoints, code/config, data recipe/provenance, token budget, seeds or uncertainty, and the same evaluation harness before and after. Without them, report correlation rather than a causal stage claim.",
  ),
  "instruction-tuning-rlhf": evidence(
    "Behavior shaping and runtime capability solve different deficits",
    ["Behavior deficit", "The base model continues prose instead of answering concisely.", "Reviewed demonstrations and preference feedback can shape the response policy."],
    ["Fresh-fact/authority deficit", "The assistant needs today's private policy and permission to issue a refund.", "Retrieval supplies evidence; runtime authorization controls the action. More preference data cannot replace either."],
    "Map every failure to weights, current evidence, decoding, or enforced capability before selecting a training stage.",
    "A deployed assistant is polite but cites stale policy and occasionally proposes unauthorized account changes. Allocate fixes across SFT, preference/RL, retrieval, and runtime controls.",
    ["Does not fine-tune changing policy facts by default", "Uses training only for repeated behavior deficiencies", "Places identity, scope, confirmation, and audit outside the model"],
    "Refresh and permission-filter retrieval for policy evidence; add evaluation/training only for persistent citation or refusal behavior; enforce account-change authority, validation, confirmation, and receipts in runtime code.",
  ),
  "posttraining-overview": evidence(
    "A minimal stage stack and an over-engineered stack",
    ["Matched intervention", "Schema-valid answers improve with reviewed SFT examples plus deterministic parsing.", "The data, method, and metric align to a repeated behavioral target."],
    ["Category error", "A subjective reward model is added to enforce user permissions.", "Training may influence compliance, but it cannot become the authorization system."],
    "Use the smallest measured intervention that matches the failure and keep hard controls external.",
    "Design post-training for an agent that must solve exact calculations and write open-ended research reports. Allocate demonstrations, verifiers, rubrics, tools, and runtime controls with separate gates.",
    ["Uses exact verification only for checkable outcomes", "Uses multidimensional rubrics for open reports", "Evaluates tool cost/citations and keeps permissions external"],
    "Seed both behaviors with SFT/tool trajectories; use verifiable rewards for exact calculations and validated rubric-based feedback for reports; supply search at runtime; gate accuracy, grounding, cost, general regressions, and authorization separately.",
  ),
  sft: evidence(
    "A clean demonstration and a template-corrupted one",
    ["Aligned example", "Deployment chat template, assistant-only labels, and terminal token match the training contract.", "The example teaches the intended answer rather than hidden formatting artifacts."],
    ["Silent corruption", "The response is truncated or user tokens receive loss while evaluation uses a different template.", "Loss can fall even as deployed behavior degrades."],
    "Inspect decoded text and loss-bearing tokens with the exact deployment tokenizer before scaling the run.",
    "Transfer the support-ticket workshop to medical-literature summarization without training on private patient data. Define data, evaluation, and stop rules.",
    ["Uses licensed/de-identified literature examples rather than patient records", "Evaluates citation support, omissions, uncertainty, and general regressions", "Defines an abstention/escalation boundary and a baseline before training"],
    "Build reviewed public-literature demonstrations with source IDs, hold out topics/sources, compare against prompt/RAG baselines, and stop on unsupported clinical claims, lost uncertainty, or general-capability regression.",
  ),
  "preference-optimization": evidence(
    "A useful preference and a length-biased label",
    ["Clean pair", "Two answers differ mainly in correctness and evidence under a written rubric.", "Chosen/rejected log-probability differences provide a relevant relative signal."],
    ["Confounded pair", "The preferred answer is always longer and comes from one model family.", "The learner may optimize verbosity or source style instead of quality."],
    "Preference data teaches the annotation policy, including its shortcuts and biases.",
    "For a terse coding assistant and an empathetic support assistant, decide whether to use the same preference rubric and length normalization. State the diagnostics.",
    ["Defines task-specific quality dimensions", "Measures length and source-model bias", "Keeps correctness/safety slices separate from style preference"],
    "Use distinct rubrics or weighted slices: code prioritizes correctness and minimal sufficient explanation, while support includes empathy without hiding resolution accuracy. Audit preference rate by length and source, and calibrate on blinded human labels.",
  ),
  "rl-fundamentals": evidence(
    "Positive reward can still produce a negative update",
    ["Above baseline", "Reward 0.7 with baseline 0.2 gives advantage +0.5.", "The sampled action becomes more likely under a policy-gradient update."],
    ["Below baseline", "Reward 0.7 with baseline 0.9 gives advantage −0.2.", "The same positive raw reward makes the sampled action less likely because it underperformed expectation."],
    "Policy gradients use relative return or advantage for credit, not raw reward sign alone.",
    "A two-step agent gets reward only after a successful final tool result. Explain how the first action can receive credit and where variance enters.",
    ["Defines return across the delayed outcome", "Uses a value/baseline or advantage for both steps", "Notes that sampled trajectories and long horizons increase variance"],
    "Assign the terminal return back through the trajectory, estimate each state's baseline, and update each sampled action using its advantage. More trajectories, better value estimates, and advantage estimation reduce—but do not remove—variance.",
  ),
  rlhf: evidence(
    "Reward improvement and actual quality can diverge",
    ["Controlled update", "The policy improves validated reward while KL, human quality, safety slices, and response length remain within gates.", "Several independent signals support a useful change."],
    ["Reward hacking", "Reward rises as answers become verbose and formulaic, while blinded human correctness falls.", "The policy exploited the reward model; higher optimized reward is not the deployment goal."],
    "Optimize a proxy only inside an evaluation and KL-control system that can detect proxy failure.",
    "A health-support task has subjective empathy ratings and strict factual boundaries. Design preference/reward training and a release gate that cannot trade factual safety for empathy.",
    ["Separates empathy and factual/safety graders", "Uses calibrated humans or independent checks for high-risk facts", "Makes severe factual regression a blocking gate"],
    "Train relative empathy/helpfulness with clear comparisons, but use sourced factual checks and expert-reviewed high-risk slices as separate non-compensable gates. Monitor KL, length, reward disagreement, and over-refusal.",
  ),
  "tools-safety": evidence(
    "Allow safe use and block unauthorized effects",
    ["Benign read", "A valid public search call passes schema and scope checks.", "The system executes it and records the evidence rather than refusing every tool."],
    ["Injected write", "Retrieved text asks the model to upload private files.", "The runtime exposes no matching authority, labels the text untrusted, and blocks the effect even if the model is confused."],
    "Safety means a useful capability inside deterministic boundaries, not maximum refusal.",
    "A model over-refuses authorized read-only financial summaries but occasionally complies with injected transfer requests. Separate the training and runtime fixes.",
    ["Uses balanced allowed/denied examples to repair the learned boundary", "Keeps transfer authorization, confirmation, and limits in runtime code", "Evaluates both unsafe compliance and false-refusal rates"],
    "Add counterexamples and preference/evaluation slices for legitimate reads versus suspicious writes; preserve schema, identity, amount, confirmation, idempotency, and audit enforcement outside the model.",
  ),
  "tulu3-case-study": evidence(
    "Exact rewards and evolving research rubrics fit different outcomes",
    ["RLVR", "A program can verify the final arithmetic or code-test result.", "A stable binary/graded reward supports online optimization."],
    ["RLER", "A research report has multiple valid structures and evidence needs that evolve with the trajectory.", "Task-specific rubrics score coverage, citation support, synthesis, and cost without pretending there is one answer key."],
    "Reward design must match outcome verifiability and remain separate from tool authorization.",
    "Transfer the Tülu/DR Tulu recipe to an IT-remediation agent that diagnoses incidents and may restart services. Allocate stages and boundaries.",
    ["Uses SFT on valid diagnostic/tool trajectories", "Uses exact checks where logs/tests verify outcomes and rubrics for diagnosis quality", "Requires runtime service scope, approval, rollback, and audit"],
    "Seed structured diagnosis and tool use with SFT, compare response quality where subjective, use verifiers for testable fixes, and apply rubric feedback to incident synthesis. Runtime policy controls which services may restart and how rollback occurs.",
  ),
  "decoding-sampling": evidence(
    "Creative text and strict JSON need different decoding contracts",
    ["Creative ideation", "Moderate temperature/top-p produces diverse candidates that are later filtered.", "Variation is useful because several outputs can satisfy the task."],
    ["Structured output", "A schema-constrained decoder or validator requires exact keys and types.", "Unbounded sampling can create invalid syntax even when prose quality seems high."],
    "Choose decoding from the output contract and test it across representative prompts.",
    "Set decoding policies for a poetry assistant and a medication-dose extractor. Define why the policies differ and which metric blocks release.",
    ["Allows measured diversity only for poetry", "Uses constraints/low randomness and validation for extraction", "Makes incorrect or malformed dose output a blocking failure"],
    "Use diverse sampling plus human/style evaluation for poems. For extraction, use deterministic or constrained decoding, validate units/schema against evidence, abstain on ambiguity, and block release on any severe dosage error.",
  ),
  "generation-kv-cache": evidence(
    "MHA and grouped-query attention change cache memory",
    ["Full MHA cache", "Each layer stores K and V for every KV head and prior position.", "Decode reuses them but memory grows with layers × heads × sequence × head width × bytes."],
    ["GQA cache", "Many query heads share fewer KV heads.", "Cache memory falls with $h_{kv}$, while query computation and quality trade-offs remain model-specific."],
    "The cache removes repeated K/V computation; it does not remove sequential next-token generation.",
    "A service supports shared 8K prefixes for many users. Compare naive per-request caches, prefix sharing, and eviction risks, then name a correctness test.",
    ["Counts shared versus private KV blocks", "Addresses tenant isolation and invalidation", "Tests logits against an uncached reference after reuse/eviction"],
    "Deduplicate immutable prefix blocks with tenant-safe keys and reference counts, append private blocks per request, and evict only unreferenced entries. Compare cached logits/tokens with a clean full-prefill run.",
  ),
  "quantization-memory": evidence(
    "Smooth weights and outliers quantize differently",
    ["Well-scaled group", "Values occupy the quantizer range evenly.", "A group scale preserves useful distinctions with small reconstruction error."],
    ["Outlier group", "One large channel sets the scale for many small values.", "Small values collapse toward the same code unless grouping, calibration, or outlier handling changes."],
    "Bit width predicts storage; data distribution and kernels determine accuracy and speed.",
    "Choose a scheme for a memory-limited model where perplexity is stable but a rare medical slice regresses. State the next measurement and deployment decision.",
    ["Rejects aggregate perplexity as sufficient", "Measures layer/channel outliers and the rare slice", "Considers selective higher precision or no deployment"],
    "Localize error by layer/group and affected tokens, compare calibration sets and mixed-precision exceptions, and require the medical slice to meet its gate even if average memory and perplexity look good.",
  ),
  "serving-systems": evidence(
    "The same average throughput can hide very different user experience",
    ["Continuous batching", "New requests join between decode steps while finished sequences leave.", "GPU utilization and goodput improve across mixed-length traffic."],
    ["Tail queue", "One long prompt or stalled request holds a static batch.", "Average tokens/s may look acceptable while p99 TTFT and completion latency violate the SLO."],
    "Measure queue, prefill, decode, and tail latency separately; throughput alone is not a service objective.",
    "Traffic is 90% short chats and 10% long document prompts. Propose scheduling, batching, and SLO slices that prevent the long requests from starving or blocking chats.",
    ["Separates prefill-heavy and decode-heavy work", "Reports TTFT/ITL and p95/p99 by request shape", "Includes fairness or admission limits for both classes"],
    "Use continuous batching with chunked/prefill-aware scheduling or separate queues, cap oversized requests, and measure goodput plus TTFT/ITL by short/long class. Reject a policy that wins aggregate throughput by starving either class.",
  ),
  "test-time-compute": evidence(
    "Generating a correct candidate and selecting it are separate events",
    ["Reliable verifier", "Diverse samples include a correct proof and an independent checker selects it.", "Best-of-N converts extra candidates into higher final accuracy."],
    ["Verifier failure", "pass@N rises but the learned judge prefers fluent wrong proofs.", "More sampling raises oracle coverage without improving deployable accuracy."],
    "Budget candidate generation and verification as two separately evaluated systems.",
    "An easy support query and a hard theorem enter the same service. Design an adaptive budget and stop rule without claiming uncertainty perfectly predicts difficulty.",
    ["Starts both with a bounded cheap path", "Escalates using measured signals and task value", "Stops on verification, agreement, or diminishing returns with a hard cap"],
    "Answer the support query with one short pass unless validation fails. Give the theorem multiple diverse attempts plus a reliable checker; cap tokens/samples and fall back or escalate when verification remains inconclusive.",
  ),
  "context-engineering": evidence(
    "Relevant evidence and hostile instructions can occupy the same context",
    ["Clean evidence", "A retrieved policy passage is labeled, cited, and used only as factual support.", "The model can answer while authority remains in the application contract."],
    ["Injected evidence", "A passage says to ignore policy and call an unrelated privileged tool.", "It remains untrusted data; delimiters help interpretation but runtime permission prevents the action."],
    "Context controls what the model sees, not what the system authorizes.",
    "Edit a context for a legal summarizer containing system rules, user goals, two conflicting sources, and irrelevant history. State what to keep, order, label, or omit.",
    ["Preserves the task/output/uncertainty contract", "Labels source provenance and conflict", "Drops irrelevant history and refuses to treat source text as authority"],
    "Keep the application contract first, the user's scoped request, then dated/provenanced evidence with the disagreement explicit. Remove irrelevant history, require citations, and ask or abstain where authority cannot be resolved.",
  ),
  rag: evidence(
    "Retrieval failure and generation failure require different fixes",
    ["Missing evidence", "The correct policy passage never enters the top results.", "Oracle-context performance is high, so ingestion/query/reranking is the primary bottleneck."],
    ["Unused evidence", "The correct passage is ranked first, but the answer contradicts it.", "Generation, prompt, citation validation, or model capability is the primary bottleneck."],
    "Evaluate retrieval and evidence use independently before changing the entire pipeline.",
    "A multilingual RAG system has high English recall but weak Arabic answers. Design measurements that distinguish embedding, indexing, reranking, and generator failures.",
    ["Measures retrieval recall by language with labeled relevant passages", "Runs oracle-context generation in Arabic", "Checks citation entailment and permissions, not only answer fluency"],
    "Compare normal versus oracle retrieval per language, inspect embedding/reranker ranks, and score answer support with the same Arabic evidence. Fix the earliest stage whose oracle replacement closes the gap.",
  ),
  "agent-loops": evidence(
    "A bounded workflow and an unbounded agent loop",
    ["Recoverable state machine", "Known states, typed actions, retry counts, and a terminal condition are explicit.", "A failed tool returns a validated event and the orchestrator chooses a bounded recovery path."],
    ["Recursive drift", "The model repeatedly replans after the same failure without an idempotency key or budget.", "Cost grows and duplicate side effects remain possible even when reasoning text sounds sensible."],
    "The orchestrator owns state, authority, budgets, and termination; the model proposes transitions.",
    "A document workflow has three known steps but one optional branch for missing evidence. Decide whether it needs an agent and write the minimal state/event contract.",
    ["Keeps fixed steps deterministic", "Uses model choice only for the genuinely variable branch", "Defines retry, escalation, idempotency, and terminal states"],
    "Use a workflow with states ingest → validate → transform → approve. If evidence is missing, a bounded model-assisted retrieval branch may run once or escalate; every write is validated/idempotent and the run always reaches success, failure, or human review.",
  ),
  "evaluation-design": evidence(
    "A judge score can reverse after calibration",
    ["Uncalibrated result", "A judge prefers model A 65% of the time.", "The aggregate suggests shipping A."],
    ["Bias audit", "After answer order is swapped, first-position preference remains 64%; blinded humans show no A advantage.", "The ship decision changes because the instrument—not the model—caused most of the signal."],
    "Evaluator validity, uncertainty, and severe slices are part of the result, not footnotes.",
    "A new model gains 2 points overall but loses 15 points on a rare regulated slice. Write a release decision with uncertainty and adjudication steps.",
    ["Uses predefined slice severity rather than aggregate compensation", "Reports paired uncertainty and raw failures", "Calibrates/adjudicates the grader before a final claim"],
    "Block release under the high-risk regression gate, inspect paired examples with experts, verify judge agreement/bias, and report the aggregate gain without using it to erase the severe slice.",
  ),
  "security-privacy": evidence(
    "Prompt instructions and capability boundaries provide different protection",
    ["Prompt-only", "The system says ‘never reveal secrets’ while the model receives secrets and unrestricted outbound tools.", "One successful injection can still exfiltrate data because ambient authority remains."],
    ["Least privilege", "The task receives only scoped data and tools; outputs are validated and consequential calls need approval.", "A model mistake has a smaller, observable blast radius."],
    "Use prompts as defense-in-depth after deterministic isolation, authorization, and data minimization.",
    "Threat-model a resume-screening assistant that reads uploaded documents and writes interview decisions. Place controls for injection, sensitive attributes, cross-candidate leakage, and overblocking.",
    ["Maps assets, actors, and trust boundaries", "Separates document text from decision authority", "Includes privacy minimization, fairness review, and an appeal/audit path"],
    "Treat resumes as untrusted, isolate candidates, omit unnecessary sensitive attributes, constrain retrieval/tools, validate structured recommendations, require authorized human decision, and log privacy-minimized evidence for audit and appeal.",
  ),
  "observability-governance": evidence(
    "Similar cost spikes can have different root causes",
    ["Long context", "Retrieval begins returning ten times more tokens after an index change.", "Prefill latency and input cost rise; the fix belongs to retrieval/context budgets."],
    ["Tool loop", "Prompt size is stable, but a retry bug calls search six times.", "Tool spans and trajectory state reveal the cost; prompt compression would miss the cause."],
    "Trace the complete request path and connect every alert to an owner, threshold, diagnosis, and rollback.",
    "A release improves average quality but doubles p99 cost and increases privacy-redaction failures on one tenant. Construct the incident decision and rollback evidence.",
    ["Uses tenant/slice metrics rather than only averages", "Assigns owners for cost and privacy failures", "Defines rollback/canary evidence and a test added after the incident"],
    "Pause or roll back the canary under privacy and cost gates, preserve privacy-safe traces, localize the changed stage/version, notify accountable owners, and turn the failure into paired tenant and cost regression tests.",
  ),
  distillation: evidence(
    "A strong teacher can transfer both structure and error",
    ["Useful soft target", "Teacher probabilities put 0.55 on cat and 0.35 on dog.", "The student learns similarity information hidden by a one-hot cat label."],
    ["Confident error", "The teacher assigns 0.98 to a wrong label on a minority slice.", "Distillation can amplify the teacher's calibration and coverage failure unless outputs are verified or mixed with ground truth."],
    "Teacher quality must be measured on the exact student task and slices before generating supervision.",
    "Distill a long-form generator into a small support model. Decide between token-logit, sequence-response, and representation losses under limited API access.",
    ["Matches the method to available teacher signals", "Evaluates calibration and sequence quality, not only accuracy", "Includes verified human/ground-truth data for teacher blind spots"],
    "With response-only API access, use verified sequence demonstrations rather than unavailable logits; mix with trusted labels, diversify prompts, and evaluate correctness, calibration, style, latency, and known teacher-error slices.",
  ),
  lora: evidence(
    "More adapter rank cannot repair the wrong learning contract",
    ["Capacity bottleneck", "Rank-8 underfits after data, masking, learning rate, and target modules are validated.", "A controlled rank increase may improve the task at higher memory cost."],
    ["Data/template bug", "Assistant tokens are truncated and user tokens receive loss.", "Rank-256 learns the wrong signal more expensively; capacity was not the bottleneck."],
    "Tune rank only after verifying data, base capability, target modules, and the loss-bearing tokens.",
    "Choose between merged weights and runtime adapters for 20 tenants with separate domains and rollback requirements.",
    ["Accounts for base+adapter compatibility and memory", "Compares switching latency/throughput with merged serving", "Preserves provenance, isolation, and rollback"],
    "Runtime adapters preserve per-tenant switching and rollback if the server supports efficient batching/isolation; merged variants may improve simplicity or speed but multiply artifacts. Benchmark both and pin the base revision for every adapter.",
  ),
  moe: evidence(
    "Sparse FLOPs do not eliminate routing and communication cost",
    ["Balanced batch", "Top-2 routing distributes tokens within expert capacity.", "Useful specialization proceeds without excessive overflow or idle experts."],
    ["Hot expert", "Most tokens select one expert beyond its capacity.", "Tokens may be dropped/rerouted and all-to-all imbalance dominates latency despite similar nominal active FLOPs."],
    "Measure expert load, overflow, communication, memory, and task quality together.",
    "A production MoE is slower than a dense model with similar active FLOPs. Design a diagnosis across router, capacity, batch shape, and network topology.",
    ["Inspects per-expert token counts and overflow", "Measures all-to-all and small expert-batch efficiency", "Avoids concluding parameter count or FLOPs alone explains latency"],
    "Profile router distribution, capacity padding/drop policy, expert batch sizes, kernel utilization, and all-to-all by link. Compare matched workloads and adjust routing/capacity/placement only after locating the bottleneck.",
  ),
  "multimodal-models": evidence(
    "Perception failure and language-prior failure can look equally fluent",
    ["OCR bottleneck", "Small text disappears after image resizing and patching.", "The answer is wrong because evidence never reaches a usable visual representation."],
    ["Language prior", "Text is legible, but the model answers with a common invoice total instead of the displayed one.", "Evidence is present; fusion, grounding, or generation ignored it."],
    "Separate processor, perception, localization, reasoning, and language-generation stages in evaluation.",
    "Transfer the vision-language pipeline to a two-minute audio clip. Map encoder, alignment, temporal positions, token budget, and a failure-specific evaluation.",
    ["Defines audio segmentation/features and temporal order", "Explains the interface into the language model", "Separates transcription/perception errors from reasoning errors"],
    "Encode waveform segments into audio features, preserve time positions, project/resample them into the model interface, and evaluate transcription/localization separately from question answering and language-prior hallucination.",
  ),
  "interpretability-editing": evidence(
    "A readable feature and a causal mechanism are different claims",
    ["Probe result", "A classifier decodes a concept from hidden states.", "The information is present, but the model may not use that direction for the behavior."],
    ["Controlled intervention", "Activation patching changes the target behavior while sham and neighboring controls stay stable.", "This supports a scoped causal contribution, still bounded by prompts, layers, and effect size."],
    "Match claim strength to intervention, controls, locality, robustness, and persistence.",
    "An edit suppresses one false answer but fails paraphrases and changes unrelated answers. State the strongest defensible claim and the next experiment.",
    ["Calls it prompt-local suppression rather than knowledge deletion", "Reports locality and paraphrase failure", "Adds matched controls and persistence/robustness tests"],
    "The evidence supports a brittle behavioral change on tested prompts, not a localized fact edit or unlearning. Test paraphrases, neighbors, sham edits, unrelated tasks, restarts, and rephrased contexts before escalating the claim.",
  ),
};

