import type { CapstoneEvidencePack } from "../capstone-evidence";
import type { CapstoneProject } from "../capstone-projects";
import { publicPath } from "../public-path";
import { generativeSources, type GenerativeSource } from "./sources";

type Seed = { lessonId: string; title: string; outcome: string; prerequisite: string; question: string; fixture: string; baseline: string; changedCase: string; metric: string; failure: string; source: GenerativeSource; time: string };
const distributionSeedCount = 20;
const diffusionStartCount = 32;
const energyBudgets = "20, 100, and 500";

const seeds: Seed[] = [
  { lessonId: "distribution-workbench-capstone", title: "Build a distribution workbench", outcome: "Deliver a tested categorical distribution package and a changed-case rare-mode experiment.", prerequisite: "Probability, likelihood, sampling, and divergences", question: "How does finite sample count change rare-mode miss rate while exact sampler invariants remain fixed?", fixture: `a dependency-free categorical package with p=[.02,.48,.50], declared ordering, and ${distributionSeedCount} canonical seeds`, baseline: "N=100 draws per seed", changedCase: "increase to N=10,000 without changing probabilities, generator, ordering, or seed list", metric: "rare-mode miss rate plus exact normalization, replay, and support checks", failure: "tighten a frequency tolerance until a statistically valid sampler fails and diagnose the brittle test", source: generativeSources.deepLearning, time: "2–3 hours" },
  { lessonId: "latent-models-capstone", title: "Build and diagnose a minimal VAE", outcome: "Implement a small VAE and run one matched posterior-collapse intervention.", prerequisite: "Latent variables, amortized inference, ELBO, and collapse probes", question: "Does KL annealing increase repeatable latent use without crossing the reconstruction regression gate?", fixture: "a tiny 8×8 binary-shape VAE with 2D latent, three declared seeds, and one-batch overfit test", baseline: "beta=1 from step zero", changedCase: "linear KL annealing over the first 30% of matched training steps", metric: "held-out reconstruction NLL, KL distribution, active units, and paired latent-swap effect", failure: "preserve a seed where active units rise but prior samples or reconstruction cross the gate", source: generativeSources.vae, time: "5–8 hours; optional GPU" },
  { lessonId: "flow-energy-capstone", title: "Compare flows and energy sampling", outcome: "Build a verified 2D flow and EBM, then report family-specific trade-offs without false unit comparisons.", prerequisite: "Change of variables, flows, energy models, and Langevin sampling", question: "At matched target data and quality-versus-gradient-call budgets, where do flow and EBM samplers lose mode coverage?", fixture: "an eight-mode 2D ring with fixed train/validation draws, seeds, and mode boundaries", baseline: "invertible coupling flow with direct samples and exact log density", changedCase: `EBM Langevin curves at ${energyBudgets} gradient evaluations per retained chain state`, metric: "mode occupancy, precision/coverage proxy, held-out NLL where valid, round-trip error, autocorrelation, and primitive calls", failure: "retain a shared low-energy pocket or scale-overflow case and show which diagnostic catches it", source: generativeSources.realNvp, time: "5–8 hours; optional GPU" },
  { lessonId: "diffusion-model-capstone", title: "Build a small diffusion model", outcome: "Implement forward corruption, noise prediction, reverse sampling, resume, and a paired sampler study.", prerequisite: "Corruption, scores, DDPM objective, and sampler schedules", question: "At matched checkpoint and starting noises, how does reducing model evaluations change trajectory and coverage failures?", fixture: `a 16×16 synthetic-shape diffusion model with pinned schedule, ${diffusionStartCount} canonical fixed start tensors, and smoke/full profiles`, baseline: "50-evaluation ancestral or DDIM-style sampler", changedCase: "20-evaluation sampler using the same checkpoint, starts, normalization, and evaluator", metric: "held-out noise loss by timestep, fixed-start failures, fidelity/coverage proxy, model calls, and hardware-specific runtime", failure: "preserve an early trajectory divergence and determine whether schedule spacing or target conversion caused it", source: generativeSources.ddpm, time: "6–10 hours; optional GPU" },
  { lessonId: "conditional-safety-capstone", title: "Audit a conditional generator", outcome: "Produce a condition×scale×seed safety and quality matrix with a deterministic release decision.", prerequisite: "Conditional generation, CFG, inverse problems, and composition", question: "Which guidance scale first meets joint adherence without failing diversity, consistency, conflict, or memorization gates?", fixture: "three shape/color conditions, four guidance scales, ten paired seeds, conflict cases, and canary controls", baseline: "native conditional prediction at guidance w=1", changedCase: "held-out attribute composition plus a contradictory-condition request", metric: "marginal/joint adherence, within-condition diversity, consistency residual, nearest-neighbor evidence, and hard gate status", failure: "preserve an exact canary match or validator disagreement and route it through block/review authority", source: generativeSources.cfg, time: "3–5 hours" },
  { lessonId: "generative-research-capstone", title: "Run a matched generative intervention study", outcome: "Reproduce one bounded baseline and publish an original controlled experiment with all seeds and failures.", prerequisite: "A completed family capstone plus reproducible GPU experiments", question: "Does one predeclared mechanism change improve the target construct under matched budgets and non-compensable gates?", fixture: "a learner-selected released capstone implementation with smoke/full profiles and machine-readable artifacts", baseline: "the reproduced pinned configuration passing its acceptance gate", changedCase: "one schedule, objective, architecture, sampler, or data intervention chosen before final execution", metric: "paired seed-level effect and interval, quality/cost curves, failure gates, and construct-specific slices", failure: "retain every NaN, excluded run, negative result, and strongest counterexample with a diagnostic retry", source: generativeSources.reproducibility, time: "8–16 hours; optional GPU" },
];

function project(seed: Seed): CapstoneProject {
  return { lessonId: seed.lessonId, title: seed.title, outcome: seed.outcome, estimatedTime: seed.time,
    prerequisites: [seed.prerequisite, "Python 3 and local deterministic tests", "Evidence labels and version control"],
    materials: [seed.fixture, `Dependency-free starter: ${publicPath("capstone-artifacts/generative/generative_capstone_starter.py")}`, "The lesson code ladder and downloadable reference JSON", "A local CPU environment for required checks", "Optional pinned GPU service for the labeled extension"],
    deliverables: [{ title: "Pinned build", description: `Implement ${seed.fixture} with assertions, run manifest, and failure log.` }, { title: "Matched changed-case study", description: `${seed.baseline}; then ${seed.changedCase}.` }, { title: "Evidence package", description: `Raw rows for ${seed.metric}, decision, limitations, and retry.` }],
    stages: [
      { id: "specify", title: "Specify before building", goal: "Make the build and experiment falsifiable.", instructions: [seed.question, `Define ${seed.fixture}.`, `Predeclare ${seed.metric}, seed list, matched budget, stop rule, and rejection threshold.`], checkpoint: "Another learner can predict pass, reject, and invalid outcomes before code runs.", hint: "Write exact input/output types and evidence units; avoid words such as better without a measurement.", workspacePrompt: "Record question, hypothesis, interfaces, constants, budget, seeds, metric, threshold, and stop rule." },
      { id: "build", title: "Build and verify the mechanism", goal: "Create the smallest complete working system and prove its deterministic contracts.", instructions: [`Run python3 generative_capstone_starter.py --project ${seed.lessonId} --output ${seed.lessonId}-starter.json; expect every printed check to be true. This executes a small mechanism fixture, not model training.`, `Replace the named fixture with ${seed.baseline} while retaining the manifest, raw-row, check, and evidence-boundary schema.`, "Run shape, arithmetic, overfit or round-trip, seed replay, checkpoint, and failure assertions relevant to the family.", "Preserve a hand-calculated trace and the first implementation failure."], checkpoint: "Starter checks pass, then required local system tests pass and every output can be regenerated from the manifest.", hint: "Do not move to a long run until one tiny batch or analytic fixture behaves exactly as predicted.", workspacePrompt: "Record starter output, implementation commands, environment, invariant results, discrepancy, fix, and baseline acceptance decision." },
      { id: "intervene", title: "Run the changed case", goal: "Change one factor under a matched comparison.", instructions: [`Run this changed case: ${seed.changedCase}.`, `Preserve all rows for ${seed.metric}.`, `Force or retain this failure: ${seed.failure}.`], checkpoint: "Every declared seed/case has an artifact or a justified predeclared exclusion, and budgets match.", hint: "A failed run is part of treatment reliability, not a row to delete.", workspacePrompt: "Paste raw rows, paired effects, uncertainty, failure diagnosis, retry, and any remaining confound." },
      { id: "decide", title: "Decide and package", goal: "Apply the original rule and make the evidence inspectable.", instructions: ["Apply hard gates before trade-offs and do not move thresholds after seeing results.", "Write a bounded conclusion, strongest alternative explanation, and the next falsifying experiment.", "Export manifest, raw rows, checks, logs, samples, failures, decision, and evidence boundary."], checkpoint: "Readable report and machine-readable artifact agree; null or negative results remain publishable.", hint: "State the exact dataset, model, intervention, seed set, budget, and metric in the conclusion.", workspacePrompt: "Write decision, bounded claim, failure scope, alternatives, residual risk, and next experiment." },
    ],
    rubric: [{ criterion: "Working system", developing: "Only a diagram or partial class exists.", proficient: "End-to-end interfaces and local checks run.", excellent: "Independent invariant, resume, and failure-injection tests pass." }, { criterion: "Experimental control", developing: "Treatment changes several factors or cherry-picks outputs.", proficient: "One change, matched budget, and all rows are preserved.", excellent: "Paired design, uncertainty, stop rule, and alternative test are predeclared." }, { criterion: "Failure learning", developing: "Failures are hidden or called noise.", proficient: "One failure is preserved and diagnosed.", excellent: "A targeted retry distinguishes competing causal explanations." }, { criterion: "Evidence honesty", developing: "Fixtures or samples become universal claims.", proficient: "Claims stay within provenance and metrics.", excellent: "Every stronger claim names missing evidence and a concrete next reproduction." }],
    exemplar: { title: "A bounded decision-fixture reference", summary: `The reference specifies ${seed.fixture}, predeclares ${seed.baseline} and ${seed.changedCase}, and shows the artifact schema and decision logic for ${seed.metric}, including ${seed.failure}. Its deterministic or planned rows do not claim that a model was trained, a baseline was reproduced, or an intervention was executed.`, decisions: ["Correctness gates required before a future intervention are explicit.", "The complete declared matrix stays visible, including planned or null cells.", "The decision fixture shows how a null, negative, or failed outcome would be reported without inventing execution evidence."] },
    reflection: ["Which invariant prevented the most expensive mistaken interpretation?", "Which confound remains most capable of reversing the result?", "What single next experiment would most efficiently falsify your conclusion?"],
  };
}

export const generativeCapstoneProjects = Object.fromEntries(seeds.map((seed) => [seed.lessonId, project(seed)])) as Record<string, CapstoneProject>;

export const generativeCapstoneEvidencePacks = Object.fromEntries(seeds.map((seed) => [seed.lessonId, {
  starter: { title: `${seed.title} evidence frame`, fields: [{ field: "Question and falsifier", help: "Commit comparison and rejection before final results.", example: seed.question }, { field: "Fixture and provenance", help: "Pin interfaces, revisions, data, seeds, and evidence type.", example: seed.fixture }, { field: "Baseline and intervention", help: "Name the matched control and single changed factor.", example: `${seed.baseline}; ${seed.changedCase}` }, { field: "Measurement and failure", help: "Keep raw units, gates, and failure evidence.", example: `${seed.metric}; ${seed.failure}` }] },
  reference: { title: `Reviewed evidence-contract reference for ${seed.title.toLowerCase()}`, sections: [{ heading: "1 · Contract", content: `${seed.question} The reference specifies ${seed.fixture} and labels deterministic fixtures, planned cells, and any future measured run separately.` }, { heading: "2 · Runnable mechanism start", content: `Run the downloadable starter with --project ${seed.lessonId}; every printed check should be true. That proves local fixture wiring only. Replace its named mechanism with the working system while preserving the checks and evidence schema.` }, { heading: "3 · Baseline specification", content: `The proposed baseline is ${seed.baseline}. The artifact names the correctness, smoke, checkpoint, and seed-replay gates that an executed baseline must pass; it does not claim they ran unless a row carries reviewed execution provenance.` }, { heading: "4 · Intervention specification", content: `The proposed changed case is ${seed.changedCase}. Every canonical fixture or planned row remains in the artifact, including the decision example: ${seed.failure}. Planned or null cells are instructions, not observations.` }, { heading: "5 · Decision fixture", content: `The predeclared evidence is ${seed.metric}. The deterministic reference demonstrates gate order and bounded reporting only; a learner conclusion must come from the learner's pinned implementation, data, seeds, budgets, and preserved run rows.` }] },
  checks: [{ label: "Question, fixture, and evidence type are explicit", terms: ["question", "fixture", "evidence"] }, { label: "Starter and working-system checks are preserved", terms: ["starter", "check", "system"] }, { label: "Baseline and treatment have matched budgets", terms: ["baseline", "treatment", "budget"] }, { label: "Failure, uncertainty, and boundary are preserved", terms: ["failure", "uncertainty", "boundary"] }],
  sources: [{ label: seed.source.title, revision: "Primary or official source reviewed 15 Jul 2026; pin mutable implementations before execution", url: seed.source.url, readFor: seed.source.note, kind: seed.source.kind === "Paper" ? "PRIMARY / FOUNDATIONAL PAPER" : "OFFICIAL / TECHNICAL SOURCE" }],
} satisfies CapstoneEvidencePack])) as Record<string, CapstoneEvidencePack>;

export const generativeCapstoneArtifactFiles = Object.fromEntries(seeds.map((seed) => [seed.lessonId, { label: `${seed.title} · JSON`, url: publicPath(`capstone-artifacts/generative/${seed.lessonId}.json`), contents: ["starter command and expected checks", "run manifest", "complete canonical fixture/planned matrix", "execution-status labels", "failure decision fixture", "bounded evidence rule"] }])) as Record<string, { label: string; url: string; contents: string[] }>;
