import type { CodeGuidance } from "../activity-info";
import type { LessonCodeExample } from "../code-examples";

const lines = (...parts: string[]) => parts.join("\n");
const run = (
  requirements = "Python 3 standard library only. The values are deterministic teaching fixtures.",
): CodeGuidance => ({ mode: "run", requirements });
const pseudo = (
  requirements = "No runtime is required. Trace the state, timing, and evidence boundary line by line.",
): CodeGuidance => ({ mode: "pseudocode", requirements });
const item = (
  title: string,
  setup: string,
  predict: string,
  code: string[],
  observe: string,
  tryIt: string,
): LessonCodeExample => ({
  title,
  language: "Python · local fixture",
  setup,
  predict,
  code: lines(...code),
  observe,
  tryIt,
});

export const worldModelCodeExamples: Record<string, LessonCodeExample> = {
  "world-models": item(
    "Separate model imagination from environment evidence",
    "The interface records who produced each transition.",
    "Which row can support a measured-environment claim?",
    [
      "rows = [",
      "  {'source':'model', 'next':1.8},",
      "  {'source':'environment', 'next':1.2},",
      "]",
      "for row in rows: print(row['source'], row['next'])",
    ],
    "Only the environment row is a measurement; the model row is a conditional prediction.",
    "Add a replay fixture source and write the strongest claim it supports.",
  ),
  "dynamics-tensors": item(
    "Align states and actions in time",
    "Each action predicts the state after it.",
    "How many transition pairs exist for seven states?",
    [
      "states = list(range(7))",
      "actions = [1] * 6",
      "pairs = list(zip(states[:-1], actions, states[1:]))",
      "assert len(pairs) == 6",
      "print(pairs[:2])",
    ],
    "The final state has no following action; slicing creates six aligned pairs.",
    "Delete one action and make the assertion fail before repairing the data contract.",
  ),
  "stochastic-futures": item(
    "Preserve a distribution instead of an impossible mean",
    "Two outcomes are equally likely.",
    "Is the expected next state necessarily reachable?",
    [
      "outcomes = [-2, 2]",
      "expected = sum(outcomes) / len(outcomes)",
      "print('outcomes', outcomes, 'mean', expected)",
    ],
    "The mean is zero even though zero is not an outcome in this fixture.",
    "Change probabilities to 0.8/0.2 and calculate both mean and outcome support.",
  ),
  "learning-dynamics": item(
    "Differentiate a scalar transition",
    "One gradient step updates a learned dynamics weight.",
    "Will the weight rise or fall for the stated target?",
    [
      "z, action, target, w, lr = 2, 1, 4, 1.0, 0.1",
      "prediction = w*z + action",
      "gradient = 2*(prediction-target)*z",
      "w -= lr*gradient",
      "print(prediction, gradient, w)",
    ],
    "The negative gradient makes the weight rise from 1.0 to 1.4.",
    "Run a second forward calculation and verify that squared error falls.",
  ),
  "belief-states-filtering": item(
    "Perform one Bayes observation update",
    "A prior is multiplied by likelihood then normalized.",
    "Does evidence favor hidden state A?",
    [
      "prior = [0.5, 0.5]",
      "likelihood = [0.8, 0.2]",
      "raw = [p*l for p,l in zip(prior, likelihood)]",
      "posterior = [x/sum(raw) for x in raw]",
      "print(posterior)",
    ],
    "Posterior mass becomes [0.8, 0.2] and still sums to one.",
    "Set both likelihoods to zero and design an explicit impossible-observation policy.",
  ),
  "autoencoders-latents": item(
    "Audit bottleneck shape and loss weighting",
    "A tiny vector stands in for a high-dimensional observation.",
    "Which input coordinate dominates squared loss?",
    [
      "target = [0, 0, 1]",
      "reconstruction = [0, 2, 0]",
      "errors = [(a-b)**2 for a,b in zip(target,reconstruction)]",
      "print(errors, sum(errors))",
    ],
    "The large background-like error 4 dominates the smaller control-feature error 1.",
    "Assign explicit feature weights and explain the new trade-off.",
  ),
  "stochastic-latents-vaes": item(
    "Reparameterize a latent sample",
    "Noise stays explicit while gradients can reach mean and scale.",
    "What sample results from the fixed values?",
    [
      "mu = [1, 0]",
      "sigma = [0.5, 2]",
      "epsilon = [2, -0.5]",
      "z = [m+s*e for m,s,e in zip(mu,sigma,epsilon)]",
      "print(z)",
    ],
    "Coordinate-wise reparameterization $z=\\mu+\\sigma\\epsilon$ produces the sample [2.0, -1.0].",
    "Use epsilon [0,0] and distinguish the posterior mean from a general sample.",
  ),
  "action-conditioned-transitions": item(
    "Intervene on the action",
    "The start state stays fixed while action changes.",
    "Should the two next states differ?",
    [
      "def transition(z, action): return 0.8*z + 0.6*action",
      "start = 2",
      "for action in [-1, 1]: print(action, transition(start, action))",
    ],
    "Opposite actions produce different predictions from the same state.",
    "Remove action from the function and name which intervention test now fails.",
  ),
  "recurrent-state-space": item(
    "Keep prior and posterior inputs separate",
    "The prior cannot see the current observation; the posterior can.",
    "Which function is legal during imagination?",
    [
      "def prior(memory, action): return memory + action",
      "def posterior(prior_state, observation): return 0.5*(prior_state+observation)",
      "p = prior(1.0, 0.2)",
      "q = posterior(p, -0.8)",
      "print(p, q)",
    ],
    "Imagination can call prior; filtering uses posterior after real evidence arrives.",
    "Write an assertion that the prior signature contains no observation argument.",
  ),
  "prediction-targets": item(
    "Align rewards and continuation with transitions",
    "Each reward belongs to the action that produced the next state.",
    "Which reward trains transition zero?",
    [
      "states = ['s0','s1','s2']",
      "actions = ['a0','a1']",
      "rewards = [2, -1]",
      "for t,a in enumerate(actions): print(states[t], a, rewards[t], states[t+1])",
    ],
    "Reward 2 is attached to s0, a0, s1.",
    "Add a terminal flag and mask all targets after termination.",
  ),
  "multistep-overshooting": item(
    "Measure free-running drift by horizon",
    "A signed transition bias is composed repeatedly.",
    "At which horizon does drift exceed 0.5?",
    [
      "bias = 0.08",
      "for horizon in [1,4,8,12]:",
      "    print(horizon, round(horizon*bias, 2))",
    ],
    "The approximation first exceeds 0.5 at horizon 8 among the listed checks.",
    "Replace signed bias with alternating signs and explain why the sum changes.",
  ),
  "uncertainty-ensembles": item(
    "Compute ensemble disagreement",
    "Three predictions share a mean but differ in spread.",
    "Which set should the toy disagreement gate review?",
    [
      "from statistics import pstdev",
      "sets = [[1.0,1.1,0.9], [0,1,2]]",
      "for values in sets: print(round(pstdev(values), 3), pstdev(values)>0.25)",
    ],
    "The wide set crosses the 0.25 fixture threshold.",
    "Add [3.0,3.1,2.9] with target -1 and explain shared bias.",
  ),
  "imagined-rollouts": item(
    "Accumulate a terminated imagined return",
    "Rewards stop contributing after predicted termination.",
    "What return follows the three rewards?",
    [
      "rewards = [2,1,4]",
      "gamma = 0.9",
      "total = sum((gamma**t)*r for t,r in enumerate(rewards))",
      "print(round(total, 2))",
    ],
    "The finite return is 6.14 before uncertainty or terminal-value adjustments.",
    "Insert a continuation probability of 0.5 before the final reward.",
  ),
  "shooting-cem": item(
    "Execute one CEM elite refit",
    "Scores choose elites; action values set the next proposal.",
    "Which two actions survive the score ranking, and what mean do they set for the next proposal?",
    [
      "actions = [-1,0,1,2]",
      "scores = [0,3,5,1]",
      "elite = [a for _,a in sorted(zip(scores,actions), reverse=True)[:2]]",
      "print(elite, sum(elite)/len(elite))",
    ],
    "Actions 1 and 0 survive and set mean 0.5.",
    "Compute proposal spread and add a minimum-variance floor.",
  ),
  "model-predictive-control": item(
    "Execute only the first MPC action",
    "A new observation invalidates the remaining open-loop plan.",
    "Which action reaches the environment before replanning?",
    [
      "plan = ['right','right','up']",
      "executed = plan.pop(0)",
      "observation = 'unexpected slip'",
      "print(executed, observation, 'replan now')",
    ],
    "Only the first right action executes; the stale tail is not trusted.",
    "Write a warm start that shifts the tail but still re-evaluates it from the new state.",
  ),
  "actor-critic-lambda": item(
    "Compute λ-returns backward with continuation",
    "The fixture keeps reward timing, continuation, bootstrap values, and stopped critic-target ownership explicit.",
    "What are $G_0^\\lambda$ for $\\lambda=0$, $0.5$, and $1$?",
    [
      "rewards = [1.0, 2.0, 3.0]",
      "continuations = [1.0, 1.0, 0.0]",
      "next_values = [4.0, 5.0, 0.0]",
      "gamma = 0.9",
      "",
      "def lambda_returns(lam):",
      "    target = 0.0  # ignored wherever continuation is zero",
      "    returns = [0.0] * len(rewards)",
      "    for t in reversed(range(len(rewards))):",
      "        mixed = (1-lam)*next_values[t] + lam*target",
      "        target = rewards[t] + gamma*continuations[t]*mixed",
      "        returns[t] = target",
      "    return returns  # detach these targets before critic regression",
      "",
      "for lam in [0.0, 0.5, 1.0]:",
      "    values = lambda_returns(lam)",
      "    print(lam, [round(x, 2) for x in values])",
    ],
    "The three return lists are [4.6, 6.5, 3.0], [5.32, 5.6, 3.0], and [5.23, 4.7, 3.0]. Continuation zero makes the final target exactly reward 3; these detached targets train critic outputs, while actor parameters receive a separate action-improvement signal.",
    "Change the middle continuation to zero. Predict which earlier targets can still depend on reward 3, then verify the backward trace.",
  ),
  "muzero-tree-search": item(
    "Back up one learned-model edge",
    "The edge reward precedes a discounted child value.",
    "What value travels to the parent?",
    [
      "reward, gamma, child_value = 2, 0.5, 4",
      "edge_return = reward + gamma*child_value",
      "print(edge_return)",
    ],
    "The backed-up value is 4 before visit normalization or player perspective.",
    "Add two actions with visit counts and derive the improved policy target.",
  ),
  "video-tokenization": item(
    "Count spatiotemporal tokens",
    "Patch size and temporal stride independently set the interface. Temporal tubes start at zero-based anchors 0, stride, 2·stride, … while the anchor remains below the frame count; the final short tube is padded or dropped only by an explicit boundary policy.",
    "How many tokens represent the 16-frame clip, and how many temporal anchors remain when 10 frames use stride 4?",
    [
      "from math import ceil",
      "frames, height, width = 16, 64, 64",
      "patch, stride = 8, 2",
      "anchors = list(range(0, frames, stride))",
      "tokens = len(anchors)*(height//patch)*(width//patch)",
      "assert tokens == 512",
      "changed_frames, changed_stride = 10, 4",
      "changed_anchors = list(range(0, changed_frames, changed_stride))",
      "assert changed_anchors == [0, 4, 8]",
      "assert len(changed_anchors) == ceil(changed_frames/changed_stride) == 3",
      "print(tokens, changed_anchors)",
    ],
    "The first clip has eight temporal anchors and 512 tokens. The changed case has anchors [0,4,8], so zero-based enumeration agrees with ceil(10/4)=3 rather than floor division.",
    "Set the changed-case boundary policy to drop incomplete final tubes, remove anchor 8 explicitly, and explain why that policy differs from the padded-tube count.",
  ),
  "world-model-evaluation": item(
    "Expose a critical slice hidden by an average",
    "Common cases dominate a frequency-weighted score.",
    "Can the average pass while the critical slice fails?",
    [
      "common_ok, common_n = 855, 900",
      "critical_ok, critical_n = 50, 100",
      "overall = (common_ok+critical_ok)/(common_n+critical_n)",
      "print(round(overall,3), critical_ok/critical_n)",
    ],
    "Overall accuracy is 90.5% while the critical slice is only 50%.",
    "Add predeclared gates and make the deployment decision deterministic.",
  ),
  "safe-constrained-planning": item(
    "Filter feasibility before reward",
    "Chance constraints decide which candidates may be ranked.",
    "Which indices remain feasible?",
    [
      "risk = [0.02,0.07,0.04]",
      "reward = [3,10,6]",
      "feasible = [i for i,p in enumerate(risk) if p < 0.05]",
      "chosen = max(feasible, key=lambda i: reward[i])",
      "print(feasible, chosen)",
    ],
    "Candidates 0 and 2 pass; candidate 2 wins reward within that set.",
    "Make every candidate infeasible and route to an explicit fallback.",
  ),
};

export const worldModelCodeGuidance: Record<string, CodeGuidance> =
  Object.fromEntries(
    Object.keys(worldModelCodeExamples).map((id) => [
      id,
      id === "world-models" || id === "recurrent-state-space"
        ? pseudo()
        : run(),
    ]),
  );
