import type { ResourceKind } from "../lesson-guides";

export type WorldModelResource = { title: string; url: string; kind: ResourceKind; note: string };

const paper = (title: string, url: string, note: string): WorldModelResource => ({ title, url, kind: "Paper", note });
const documentation = (title: string, url: string, note: string): WorldModelResource => ({ title, url, kind: "Documentation", note });
const article = (title: string, url: string, note: string): WorldModelResource => ({ title, url, kind: "Article", note });
const course = (title: string, url: string, note: string): WorldModelResource => ({ title, url, kind: "Course", note });

export const wmSources = {
  worldModels: paper("World Models · Ha and Schmidhuber (2018)", "https://arxiv.org/abs/1803.10122", "Verify the VAE, recurrent dynamics, controller split, and the bounded claim about training inside a learned dream."),
  planet: paper("Learning Latent Dynamics for Planning from Pixels · PlaNet", "https://proceedings.mlr.press/v97/hafner19a.html", "Inspect the recurrent state-space model, deterministic and stochastic state, latent overshooting, and online planning contract."),
  dreamer: paper("Dream to Control: Learning Behaviors by Latent Imagination", "https://arxiv.org/abs/1912.01603", "Trace how a learned latent dynamics model supplies imagined trajectories for actor and value learning."),
  dreamerV3: paper("Mastering Diverse Domains through World Models · DreamerV3", "https://arxiv.org/abs/2301.04104", "Verify the single-configuration claim, normalization and balancing mechanisms, evaluation domains, and reported limitations."),
  dyna: paper("Dyna, an Integrated Architecture for Learning, Planning, and Reacting", "https://doi.org/10.1016/0004-3702(91)90020-D", "Trace how real experience, learned transition predictions, planning updates, and action selection interact in the original Dyna architecture."),
  muzero: paper("Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model", "https://www.nature.com/articles/s41586-020-03051-4", "Inspect the representation, dynamics, prediction functions, tree search, and the fact that MuZero predicts planning-relevant quantities rather than reconstructing observations."),
  tdmpc: paper("Temporal Difference Learning for Model Predictive Control", "https://proceedings.mlr.press/v162/hansen22a.html", "Verify how short-horizon latent planning and a terminal value estimate divide local and long-term prediction work."),
  vae: paper("Auto-Encoding Variational Bayes", "https://arxiv.org/abs/1312.6114", "Review the latent-variable objective, reparameterization estimator, and distinction between reconstruction and prior regularization."),
  jepa: paper("Revisiting Feature Prediction for Learning Visual Representations from Video · V-JEPA", "https://ai.meta.com/research/publications/revisiting-feature-prediction-for-learning-visual-representations-from-video/", "Verify the feature-prediction objective and the absence of pixel reconstruction, text supervision, and negative examples in the reported setup."),
  vjepa2: paper("V-JEPA 2: Understanding, Prediction and Planning", "https://ai.meta.com/research/publications/v-jepa-2-self-supervised-video-models-enable-understanding-prediction-and-planning/", "Inspect the separation between action-free video pretraining and action-conditioned robot post-training, including the exact evidence boundary."),
  genie: paper("Genie: Generative Interactive Environments", "https://deepmind.google/research/publications/60474/", "Inspect the spatiotemporal tokenizer, autoregressive dynamics, learned latent actions, training data, and action-controllability claim."),
  genie3: documentation("Genie 3 official release report · reviewed 14 Jul 2026", "https://deepmind.google/blog/genie-3-a-new-frontier-for-world-models/", "Treat the real-time interaction, resolution, and consistency statements as official release evidence, not a peer-reviewed benchmark reproduction."),
  mbrlSurvey: article("Model-Based Reinforcement Learning: A Survey", "https://arxiv.org/abs/2006.16712", "Use this secondary survey for taxonomy across model learning, planning, data collection, uncertainty, and failure modes; follow its primary citations for algorithm-specific claims."),
  rssmCode: documentation("DreamerV3 official implementation", "https://github.com/danijar/dreamerv3", "Inspect current configuration, replay, world-model losses, imagination code, and evaluation scripts; pin a commit before reproducing behavior."),
  controlSuite: paper("DeepMind Control Suite", "https://arxiv.org/abs/1801.00690", "Verify task definitions, observation and action interfaces, and why simulator scores do not establish real-robot safety."),
  safeMpc: paper("Safe Model-based Reinforcement Learning with Stability Guarantees", "https://proceedings.neurips.cc/paper/2017/hash/766ebcd59621e305170616ba3d3dac32-Abstract.html", "Inspect how a safety constraint and fallback controller narrow what learned-model exploration may execute; do not generalize the theorem beyond its assumptions."),
  domainRandomization: paper("Domain Randomization for Transferring Deep Neural Networks from Simulation to the Real World", "https://arxiv.org/abs/1703.06907", "Review what is randomized, the transfer protocol, and why randomized simulation coverage is not proof that the real domain is covered."),
  slotAttention: paper("Object-Centric Learning with Slot Attention", "https://arxiv.org/abs/2006.15055", "Inspect iterative competitive attention, slot permutation symmetry, and the evidence needed before assigning object identity to a slot."),
  neuralOde: paper("Neural Ordinary Differential Equations", "https://arxiv.org/abs/1806.07366", "Verify the continuous-time state derivative formulation and distinguish numerical integration accuracy from physical-model validity."),
  causalRepresentation: paper("Towards Causal Representation Learning", "https://arxiv.org/abs/2102.11107", "Use the research agenda to distinguish observational prediction from identifiable causal variables and intervention evidence."),
  causalInferenceOverview: paper("Causal Inference in Statistics: An Overview", "https://projecteuclid.org/journals/statistics-surveys/volume-3/issue-none/Causal-inference-in-statistics-An-overview/10.1214/09-SS057.full", "Verify the structural-causal-model distinction among conditioning, intervention, counterfactual queries, and the assumptions required for identification."),
  pytorchAutograd: documentation("PyTorch autograd mechanics · reviewed 14 Jul 2026", "https://docs.pytorch.org/docs/stable/notes/autograd.html", "Verify reverse-mode graph construction, saved tensors, gradient accumulation, and the exact boundary between differentiation and the optimizer."),
  rlBook: course("Reinforcement Learning: An Introduction · Sutton and Barto", "http://incompleteideas.net/book/the-book-2nd.html", "Use Chapters 3–4 to verify returns, policies, values, Markov decision processes, and Bellman equations before mapping them into learned-model planning."),
  pomdp: paper("Planning and Acting in Partially Observable Stochastic Domains", "https://doi.org/10.1016/S0004-3702(98)00023-X", "Verify the POMDP observation model, belief-state update, and the assumptions under which belief is a sufficient information state."),
  calibration: paper("On Calibration of Modern Neural Networks", "https://proceedings.mlr.press/v70/guo17a.html", "Inspect reliability diagrams, expected calibration error, and the distinction between predictive accuracy and calibrated confidence."),
  deepEnsembles: paper("Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles", "https://papers.nips.cc/paper_files/paper/2017/hash/9ef2ed4b7fd2c810847ffa5fa85bce38-Abstract.html", "Verify the independently initialized ensemble method, proper scoring evaluation, and why ensemble agreement is not a correctness certificate."),
  prioritizedReplay: paper("Prioritized Experience Replay", "https://arxiv.org/abs/1511.05952", "Inspect the replay record, priority sampling, importance corrections, and the difference between sampling policy and environment coverage."),
  cem: paper("The Cross-Entropy Method for Combinatorial and Continuous Optimization", "https://doi.org/10.1023/A:1010091220143", "Verify the sample–elite–refit optimization loop and the assumptions behind concentrating a proposal distribution."),
  differentiableMpc: paper("Differentiable MPC for End-to-end Planning and Control", "https://papers.nips.cc/paper_files/paper/2018/hash/ba6d843eb4251a4526ce65d1807a9309-Abstract.html", "Inspect how gradients pass through a constrained planner, then distinguish differentiating controller parameters from optimizing candidate actions through a rollout."),
  universalPlanningNetworks: paper("Universal Planning Networks", "https://proceedings.mlr.press/v80/srinivas18b.html", "Inspect the explicit gradient-based planning loop over actions in a learned latent space and the task/evaluation boundary of the published visuomotor experiments."),
  videoDiffusion: paper("Video Diffusion Models", "https://arxiv.org/abs/2204.03458", "Verify the forward-noise/reverse-denoising video objective and conditional sampling; do not compare a denoising pass with one autoregressive token decision as equal work."),
  mbpo: paper("When to Trust Your Model: Model-Based Policy Optimization", "https://papers.nips.cc/paper/2019/hash/5faf461eff3099671ad63c6f3f094f7f-Abstract.html", "Inspect why short model rollouts can limit compounding bias and how model generalization bounds constrain imagined-data use."),
  plannerOverfitting: paper("Mitigating Planner Overfitting in Model-Based Reinforcement Learning", "https://arxiv.org/abs/1812.01129", "Inspect how increasingly optimized plans can exploit learned-model errors and how plan regularization changes that failure; keep the paper's evaluated settings attached to the claim."),
  simulatorCalibration: paper("A User’s Guide to Calibrating Robotic Simulators", "https://proceedings.mlr.press/v155/mehta21a.html", "Compare parameter estimation, calibration evidence, trajectory discrepancies, and identifiability limits before treating simulator fit as reality."),
  persistentExcitation: paper("A Note on Persistency of Excitation", "https://doi.org/10.1016/j.sysconle.2004.09.003", "Verify why sufficiently informative input sequences are required to span and identify the behavior of the stated controllable linear system; do not generalize its conditions unchanged to nonlinear contact dynamics."),
  mlTestScore: paper("What’s Your ML Test Score? A Rubric for ML Production Systems", "https://research.google/pubs/whats-your-ml-test-score-a-rubric-for-ml-production-systems/", "Use the production-readiness tests to audit versioned data/features, model validation, monitoring, rollback, and operational ownership."),
  objectWorldModels: paper("Improving Generative Imagination in Object-Centric World Models", "https://proceedings.mlr.press/v119/lin20f.html", "Inspect object tracking, interaction dynamics, occlusion, and multimodal imagination; separate those claims from Slot Attention segmentation."),
  hierarchicalWorldModels: paper("Exploring the Limits of Hierarchical World Models in Reinforcement Learning", "https://arxiv.org/abs/2406.00483", "Inspect the explicit multi-level temporal abstraction, top-down goals, model-exploitation failure, and bounded empirical conclusions."),
  equivariantWorldModels: paper("Learning Symmetric Embeddings for Equivariant World Models", "https://proceedings.mlr.press/v162/park22a.html", "Verify the symmetry/equivariance world-model objective, learned group actions, and the transformations evaluated in the published experiments."),
  egnn: paper("E(n) Equivariant Graph Neural Networks", "https://proceedings.mlr.press/v139/satorras21a.html", "Inspect which rotations, translations, reflections, and permutations are guaranteed by the architecture and how it is evaluated on dynamics."),
  dynalang: paper("Learning to Model the World With Language · Dynalang", "https://proceedings.mlr.press/v235/lin24g.html", "Trace how text and image representations enter a multimodal world model and imagined policy learning, including the environments and grounding limits actually evaluated."),
  osfPreregistration: documentation("OSF Registrations and preregistration guidance · reviewed 14 Jul 2026", "https://help.osf.io/article/330-welcome-to-registrations", "Verify which study fields become frozen, how amendments are recorded, and why exploratory analyses must remain distinguishable from preregistered tests."),
} as const;
